### ISSUE TITLE
0.5.63: Windows 11: When user enables Auto-start on system boot and restarts their machine and the app opens, it is stuck @ 30%

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1010]
**Describe the bug**
As a user I find when I enable `Auto-start on system boot` and restart my laptop. When the app opens, it gets stuck @ 30%. Closing the app and reopening it resolves the issue

**To Reproduce**
1. Go to 'tari universe'
2. Click on 'Settings'
3. Scroll down to 'Auto start on system boot'
4. Click on the toggle to enable 'Auto start on system boot'
5. Close the app
6. Restart your laptop
7. Unlock your laptop
8. Tari universe app will open
9. Observe

**Expected behavior**
App should start up successfully

**Screenshots**
![Screenshot (190)](https://github.com/user-attachments/assets/c4c1de64-220b-4287-b575-c29b71e7fa0a)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 23H2

**Logs**
[universe.zip](https://github.com/user-attachments/files/17643585/universe.zip)

**Comment by Anziskavds** [comment]
Not reproduceable on MacBook Air 13 inch M1 2020 on Testnet v0.5.63

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.2 and this is no longer an issue therefore closing
