### ISSUE TITLE
Auto Startup is no longer working on Macbook

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1017]
**Describe the bug**
When a user enables the Auto Startup and they restart their machine, Tari Universe doesn't open automatically when the user logs into their machine.

**To Reproduce**
1. Go to General settings
2. Enable Auto-start on system boot on
3. Restart your laptop
4. Log in on ypur laptop
5. Tari Universe should start up automatically
6. Currently Tari Universe doesn't start up automatically

**Expected behavior**
When Auto-start on system boot is enabled Tari Universe should start up automatically when the user logs into their laptop

**Screenshots**
Not able to take a video of this because the video stops when the laptop restarts

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 on Sequoia v15.1
 - Browser & Version Testnet v0.5.63

**Comment by mmrrnn** [comment]
Works fine on m1 for me

**Comment by mmrrnn** [comment]
tested successfully on macbook with Intel

**Comment by Anziskavds** [comment]
Issue is still happening for me on my MacBook Air M1 2020.

**Comment by Misieq01** [comment]
On my Macbook Air M1 autoupdate works, tested on versions from 0.5.61 to 6.17

**Comment by Anziskavds** [comment]
This issue is still occuring for me on a MacBook Air 13 inch M1 2020 on Sequoia 15.1.1

**Comment by brianp** [comment]
Can not reproduce. 

@Anziskavds can you go to System Settings > General > Login Items & Extensions and see if you have any leftover conflicting Tari related items.

<img width="705" alt="image" src="https://github.com/user-attachments/assets/938943ca-720d-47aa-9fe2-dc2b127a0196">

<img width="485" alt="image" src="https://github.com/user-attachments/assets/530daaa3-0c37-4994-8abd-c629f46361d2">

If you have any, please toggle them off, restart your computer, and then test the feature again.

**Comment by Anziskavds** [comment]
This passed QA on both Tari Universe Beta v0.8.4 and Tari Universe Testnet v0.8.5
