### ISSUE TITLE
Annimation block no longer explode when the block time is over

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1026]
**Describe the bug**
When a users block time is over the anitmation block no longer explode. The blocks stays in a building state.

**To Reproduce**
1. Start the miner
2. Keep an eye on the block time
3. When the block time expired the animation blocks keeps building

**Expected behavior**
When the block time expires the animation blocks should explode and start building from the start again.

**Screenshots**
https://www.loom.com/share/2ed12f59c36e4a6b94b8b1efefa25a71?sid=af2bcde1-0fde-4a70-8873-ed97180adcb9

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sequoia v15.1
 - Browser & Version Testnet v0.5.63

**Logs:**
[universe-web.log](https://github.com/user-attachments/files/17649052/universe-web.log)

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.6.0 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.6.2 and this occurs intermittently

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.16 and was unable to reproduce

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.17 and was unable to reproduce

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.70 and this is no longer occurring
