### ISSUE TITLE
Typo on the 3rd slide of onboarding screen

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1041]
**Describe the bug**
On the "What is Mining?" the 3rd slide on the onboarding process of the miner we typed XTM instead of tXTM.

**To Reproduce**
1. Download the miner
2. Open the miner
3. On the 3rd slide "What is mining?" we typed XTM instead of tXTM

**Expected behavior**
We should have it as tXTM allover the miner

**Screenshots**
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/472e0042-e515-40a0-abda-51d3c1d02dff">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sequoia v15.1
 - Browser & Version Testnet v0.6.0

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.2 and this is an issue

**Comment by Tas4tari** [comment]
On the intro screen XTM is still displayed on Windows 11, app version 0.6.4:

![image](https://github.com/user-attachments/assets/aeb8c370-8020-4206-8402-628916a7a713)
