### ISSUE TITLE
As soon as the miner opens there is one single block flickering(blue/red) the jumps off. 

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1046]
**Describe the bug**
Intermittently as soon as the miner opens there is one single block, flickering and blue and red for a few times and then jumps off before the blocks starts building.

**To Reproduce**
1. Open the miner
2. Wait for the miner to open
3. Look at the blocks
4. As soon as the miner opens there is one single block, flickering and blue and red for a few times and then jumps off before the blocks starts building

**Expected behavior**
Block should start building immediately after start up.

**Video**
https://www.loom.com/share/1ad7e030187c481da3b3e83cda915ad5?sid=0d1224f8-ee9e-46a1-85b3-54fb8a2dcbfc

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 on Sequoia v15.1
 - Browser & Version Tsetnet v0.6.1

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.2 and saw this occur after a fresh install

**Comment by Tas4tari** [comment]
I've seen this on Windows 11, app version 0.6.4

**Comment by Tas4tari** [comment]
Tested on Mac Intel Core i5, app version 0.6.4 and this occurred even though the update accurred automatically

**Comment by Tas4tari** [comment]
Tested on this on Windows 11, app version 0.6.6 and this still occurs. Verified this with a fresh install

**Comment by Tas4tari** [comment]
Tested successfully on Windows 11, app version 0.6.15
