### ISSUE TITLE
0.6.1: Windows 11: Custom Mode: After changing the Custom mode a few times, the app got stuck on loading

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1047]
**Describe the bug**
I find that when I've changed the mode to Custom a few times and adjusted the number of cores to use, the app gets stuck on loading

**To Reproduce**
1. Go to 'tari universe'
2. App should be mining
3. Click on Mode
4. Change to custom mode
5. Adjust the number of cores for CPU mining and set GPU Mining to 0
6. Mode should minimize and miner should be ongoing
7. Click on Mode again, click on Custom
8. Adjust the mode for CPU to the lower end of the scale
9. Modal should close
10. View mining widget: CPU Power, Start Mining & Mode all show loading icons, only a restart resolves this

**Expected behavior**
Once CPU has been adjusted in custom mode, hash rate for CPU should display and not be stuck on load. The miner should continue mining

**Screenshots**

![Screenshot (217)](https://github.com/user-attachments/assets/43afff34-b701-417b-8caa-90bd5a8b9bd1)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, version 23H2

**Logs**
[logs.zip](https://github.com/user-attachments/files/17667273/logs.zip)

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.2 and this occurs the first time I select custom and adjust the cores for both CPU and GPU Mining:
![Screenshot (223)](https://github.com/user-attachments/assets/c34916a3-93c2-4640-bcb9-8a4022ba6ef0)

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.4 and this occurs the first time I select custom and adjust the cores for both CPU and GPU Mining:
![Screenshot (225)](https://github.com/user-attachments/assets/354ab125-77e3-4908-8f14-781a79b6e04c)

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.6 and this occurs the first time I select custom and adjust the cores for just CPU Mining

**Comment by Tas4tari** [comment]
Saw this occur on Windows 11, app version 0.6.6 this morning when I changed power usage for both CPU & GPU mining. It is still stuck on loading

**Comment by Anziskavds** [comment]
This is also happening on a MacBook Air 13 inch M1 2020 on the Testnet v0.6.9.
