### ISSUE TITLE
Telemetry toggle shows up on the Start up screen

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1051]
**Describe the bug**
I was testing https://github.com/tari-project/universe/pull/1015 but the Telemetry toggle still shows up on the Start up screen. There is no difference when the flag is set to true or false it keeps on showing up.

**To Reproduce**
1. Open Tari Universe
2. See the Telemetry toggle on the start up screen

**Expected behavior**
Telemetry toggle shouldn't show when the flag is set to false

**Screenshots**
https://www.loom.com/share/948a2539a76f4d75b3a21a3b495605a7?sid=12f6a2ea-0c62-4bf7-a1c3-453baa273871
https://www.loom.com/share/4b01d86e56c14e44badbbe9d8ea3f1f0?sid=0e6d1894-8562-4ac1-a800-44d77fe914b0

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sequoia v15.1
 - Browser & Version Testnet v0.6.4

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.6 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.14 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.15 and this is still an issue

**Comment by mmrrnn** [comment]
`allow_telemetry` flag is used for this Switch button

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.16 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.17 and this is still an issue
