### ISSUE TITLE
The Mac app can't be opened

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#1056]
**Describe the bug**
![image](https://github.com/user-attachments/assets/eae4ad67-cb32-465a-ab14-4dfb523a8177)

This can only be fixed by re-installing the app.

The issue has been present all along but seems to be rising in prevalence among users.

**Comment by brianp** [comment]
Closing while crossing fingers that #1153 solves the issue.

Please let us know if the error continues to be reported.
