### ISSUE TITLE
0.6.9: Import wallet: I find that when I import my wallet, the transactions I've done using my wallet are not visible within `Show History`

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1061]
**Describe the bug**
I find that when I import my wallet, the transactions I've done using my wallet are not visible within `Show History`. These transactions were completed using the Aurora app, however they did not show up once I imported the wallet into Tari Universe

**Emoji Address**
`🌈📟💉📎📈🗽💦🏀🍀📱💺🎬⭐🍯💼💊🔮🐚🤠👑🐙😇🐻😱🐞🍋🦆🍞🍪🍒💄🚒🐶🎰🎠🎸👅🌽💔🌲🎹🥝🍒👟🚑🍾🎀💻🍼🐵🐑🐝👃📟🚢🍣🤑🍫🎼🍫👑💔🍟😎📡🐑🐣`

**Pre-conditions**
- User should have Tari aurora installed
- User should have tXTM in Tari Aurora
- User should have done more than 2 transactions using their Tari Aurora app

**To Reproduce**
1. Go to 'tari universe'
2. Ensure app is open and mining
3. Click on Settings 
4. Click on `Wallet`
5. Scroll to seed words and click on the edit icon
6. Add in the see words for your Tari Aurora wallet
7. Click on the checkmark when done
8. User should see the app restart and the wallet imported successfully
9. On the Mining widget, scroll to `Wallet Balance`
10. Confirm wallet balance is correct and displays the same as the Aurora app
11. Click on `Show History`
12. Observe

**Expected behavior**
User should see the transactions they made on Tari Aurora visible within the `Show History` section of the tari universe app

**Screenshots**
![Screenshot (277)](https://github.com/user-attachments/assets/2a52a0ac-ac26-4051-8110-157f8929fb74)
![Screenshot (276)](https://github.com/user-attachments/assets/34d986b8-58ac-4f47-a2ee-4b2afc37bf07)
![Screenshot_20241113_143953_Tari Aurora](https://github.com/user-attachments/assets/0b731908-85c3-408d-b8b7-9858cf9b11fb)
![Screenshot_20241113_143936_Tari Aurora](https://github.com/user-attachments/assets/997d3604-5d5f-4459-8543-1cf646b9cd64)
![Screenshot_20241113_144038_Tari Aurora](https://github.com/user-attachments/assets/3549e888-357f-41fb-8d17-a748590f28a4)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, version 23H2

**Smartphone (please complete the following information):**
 - Device: Galaxy A33 5G
 - OS: One UI version: 6.1
 - OS: Android version: 14

**Comment by Anziskavds** [comment]
This is also an issue on a MacBook Air 13 inch M1 2020 on a Xiaomi Redmi Note 10

**Comment by Tas4tari** [comment]
https://nomatter.tari.com/tari/pl/dpk9aj7w9fdr3b9ep6kf4tm9ea
