### ISSUE TITLE
Monero address is reset between updates

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#1089]
**Describe the bug**
Monero address is not persisted through updates.

**Comment by Misieq01** [comment]
I've tested it with @mmrrnn on both windows and macos machines and we found that this issue is fixed on versions 0.6.0 and higher so only users that updates from versions 0.5.61 and below could encounter this inconvenience

**Comment by Misieq01** [comment]
We cannot do much for deployed versions that are already affected, maybe give some info to users on telegram so I'm closing this issue
