### ISSUE TITLE
Wallet History: Time display appears incorrectly on Wallet History

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1093]
**Describe the bug**
As a user with multiple transactions I find that the time displayed within Wallet History for transactions is incorrect. Example: 24:mm which appears in the below screenshot

![867C10AA-EE41-450B-9EAA-373B62451092-94545-000033977F0C88DD](https://github.com/user-attachments/assets/f5b65179-d460-481e-b390-254c99cbef24)

App version: 0.7.0

**Comment by Angiepeck22** [comment]
Hello @Tas4tari 
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID UNI07638
Please see the link below to our dedicated support line:
[Universe Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
