### ISSUE TITLE
0.7.4: Custom Mode: After selecting Custom mode, if I go back to the Custom mode option I find that my CPU Cores is showing as 0

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1101]
**Describe the bug**
As a user, I find that when I selected Custom Mode and I set my CPU Core value, if I go back to the Custom mode option and click on it, my CPU Cores show as 0 however the GPU levels that I set still show correctly

**To Reproduce**
1. Go to 'tari universe'
2. Click on 'Mode'
3. Scroll down to 'Custom'
4. Click on Custom
5. Set your CPU cores and your GPU threads
6. Save Changes and close the modal
7. User should be mining
8. Go back to & click on Mode
9. Scroll down to 'Custom'
10. Click on Custom
11. Observe the levels displayed, specifically for CPU Cores

**Expected behavior**
User should see the levels that they've previously set still be retained

**Screenshots**
![Screenshot (322)](https://github.com/user-attachments/assets/cf628bad-a7f6-44c4-9756-a1c69b7a474a)
![Screenshot (323)](https://github.com/user-attachments/assets/ff9d2c2f-833d-47db-a843-f673a6ae5d28)
![Screenshot (324)](https://github.com/user-attachments/assets/0467c514-1c5d-4bfe-b591-911880680465)
![Screenshot (321)](https://github.com/user-attachments/assets/03e2c947-6a45-4688-8ce2-b5d672a84462)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - OS & Version: Windows 11, VERSION 23H2

**Comment by brianp** [comment]
I think this may be related to the "Save Changes" button in some form.

**Comment by brianp** [comment]
Should be fixed with merge of #1107
