### ISSUE TITLE
Add app anon id under advanced settings

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#1114]
**Describe the bug**
Currently, users who need their Miner Anon ID for community projects (e.g., Discord bots tracking on-chain activity) must locate this information in app_config. To improve accessibility and support third-party integrations, we should expose this ID in Advanced Settings.
Rationale:

At least one community project has already requested this feature
We anticipate more community projects will need this information
The ID is frequently needed for technical support

**Comment by brianp** [comment]
We will add a read-only and copyable display of the anon id to the General settings pane.
