### ISSUE TITLE
Custom mining sliders go transparent while saving when mining

### ISSUE THREAD

**Issue by brianp** [tari-project/universe#1121]
**Describe the bug**
The circles denoting where the custom slider selection is set to transparent while saving while the miner is running.

**To Reproduce**
1. Turn the miner on Ludicrous (machine must be mining for it to occur)
2. Go to Custom mining settings
3. Change the settings
4. Select "Save Changes"
5. See the circles go transparent while applying the save

**Expected behavior**
Circles should not go transparent

**Screenshots**
![image](https://github.com/user-attachments/assets/0980919b-8bf5-4948-a050-fb79f4e610de)

https://github.com/user-attachments/assets/a5d8d7f2-9555-4c19-bcaf-9bcf3672c56c

**Desktop (please complete the following information):**
 - Mac OS & Windows

**Comment by Tas4tari** [comment]
Tested successfully on Windows 11, app version 0.8.2
