### ISSUE TITLE
0.7.8: Windows 11: Import seed words: Unable to import existing wallet via seed phrase, I am stuck on the `Importing wallet` screen and when I restart and check, the wallet was not imported

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1130]
**Describe the bug**
I was unable to import a wallet
I was stuck on the Importing wallet loading screen for more than 10 minutes. The app does not restart on it's own. 
In order to get out of this state, I have to close the app and then restart it 

**Additional Context:**
When restarted, if I go back and check the `Seed words` the wallet did not import successfully

**To Reproduce**
1. Go to Settings
2. Go to Wallet
3. Click on the edit icon
4. Remove current seed words
5. Paste in a different set of seed words
6. Click on the check mark
7. App is greyed out and `Importing wallet` loading state is shown to the user (stays like this for 10+) minutes

**Expected behavior**
When I add in new seed words, I expect the import wallet process to be quick and the app to restart on it's own

**Screenshots**
Before closing the app:
![Screenshot (371)](https://github.com/user-attachments/assets/af6fbbda-a85b-4f9c-b21e-b2dea301798a)
After restarting the app:

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 12th Gen Intel(R) Core(TM) i7-1255U 1.70 GHz, version 23H2

**Additional context**
[logs.zip](https://github.com/user-attachments/files/17923962/logs.zip)

**Comment by Tas4tari** [comment]
This is no longer occurring on 0.8.2

**Comment by Athensmo** [comment]
Hello @Tas4tari 
Thanks for reporting this, does this issue still persist? kindly let me know so we can start with the rectification procedures
