### ISSUE TITLE
0.7.8: Monero address: When user pastes Monero address and clicks on `Restart Now` they are stuck on loading

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1131]
**Describe the bug**
As a user I find that when I add in a new Monero address and click on `Restart Now` I find that I am stuck on 10+ minutes of this on the loading screen and the app does not restart. I find clicking out of the Settings modal successfully closes the modals.

**Additional Context:**
After restarting I did manage to confirm the new address retained.

**To Reproduce**
1. Go to 'tari universe'
2. Click on 'Settings'
3. Scroll down to 'Wallet'
4. Go to `Monero address` and add in a new address and click on the checkmark
5. When the Restart modal pops up, click on `Restart Now`
6. Observe

**Expected behavior**
After a few seconds app should be successfully restarted and new Monero address should be retained

**Screenshots**
![Screenshot (372)](https://github.com/user-attachments/assets/b625fdec-3be0-4235-a31a-cede46586d54)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 23H2

**Additional context**
[logs.zip](https://github.com/user-attachments/files/17924609/logs.zip)

**Comment by Tas4tari** [comment]
This is also occurring when I disable/enable Pool Mining. After clicking on `Restart Now` I'm stuck on loading and the app does not restart on it's own:
![Screenshot (373)](https://github.com/user-attachments/assets/614479a8-1892-4065-8015-798ce51405a6)

**Comment by Andesxtzgerald** [comment]
> This is also occurring when I disable/enable Pool Mining. After clicking on `Restart Now` I'm stuck on loading and the app does not restart on it's own: ![Screenshot (373)](https://private-user-images.githubusercontent.com/50987039/390118371-614479a8-1892-4065-8015-798ce51405a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTIwMTcsIm5iZiI6MTczMjY1MTcxNywicGF0aCI6Ii81MDk4NzAzOS8zOTAxMTgzNzEtNjE0NDc5YTgtMTg5Mi00MDY1LTgwMTUtNzk4Y2U1MTQwNWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDIwMDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NWRjYmE4YWFjNDRkYTRkOWFmZTAwM2I1Y2ZiYzNhYjUxMjFjMTBhOWNjZTUyODNjMzI3NzQzN2M3NDMwZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ckdpxb4OfMMHwEvFzEED-KGJDMdLM-f6GINdt0QV4dA)


Hello @Tas4tari 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID XPR17638
Please see the link below to our dedicated support line:
[Monero Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Tas4tari** [comment]
This is no longer occurring on Windows 11, app version 0.8.2
