### ISSUE TITLE
Tari and Monero wallet seed word fields don't consider being pasted into a change

### ISSUE THREAD

**Issue by brianp** [tari-project/universe#1141]
**Describe the bug**
When you paste new seeds into these two fields, neither recognize the change and result in you not being able to save

**Comment by block-scouthelp** [comment]
@brianp It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://dapps-exploreonsite.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation
