### ISSUE TITLE
I seem to be connected to a forked chain, what should I do

### ISSUE THREAD

**Issue by DWBCoreOfficial** [tari-project/universe#1145]
I seem to be connected to a forked chain, what should I do
![IMG_20241128_132253](https://github.com/user-attachments/assets/0852b64a-9c80-402e-8edf-7f8ae129444d)

**Comment by DWBCoreOfficial** [comment]
I am currently in version 0.8.1

**Comment by brianp** [comment]
This is a place of bug reporting, not technical support.

I suggest you get off the forked chain.
