### ISSUE TITLE
0.8.0: Windows: Auto update: Wallet Seed words: Seed words appear empty when I do an auto update from 0.7.7 to 0.8.0

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1147]
**Describe the bug**
As a user I find when I do an auto update from 0.7.7 to 0.8.0, when I check Wallet settings and go to view my seed words, I find that it is empty. 
**Note:**

-  I did a clean install of 0.7.7 
- I could reproduce this 2 out 2 attempts

**To Reproduce**
**Pre-conditions:**

- User should have uninstalled Tari universe app
- User should have deleted `com.tari.universe` folders from `Local` and `Roaming` folders found within the AppData folder
- User should have deleted the downloaded files

**Steps:**
1. Go to `https://github.com/tari-project/universe/releases/`
2. Click on `Tari Universe v0.7.7`
3. Scroll down to and click on ` https://github.com/tari-project/universe/releases/download/v0.7.7/Tari.Universe_0.7.7_x64_en-US.msi`
4. File should be downloaded successfully
5. Click on the file and complete set up
6. Go to desktop and double click on the `Tari Universe` app icon
7. User should be asked to auto update to 0.8.0
8. Click on yes
9. Once complete, Tari Universe app should open on version 0.8.0
10. Click on `Settings` icon
11. Click on `Wallet` in the Settings modal
12. Scroll to `Seed words` and click on the eye icon
13. User should be able to view seed words however nothing happens
14. Click on the edit icon for seed words
15. View the input box
16. User will see the seed words input box is blank

**Expected behavior**
User should be able to view their seed words

**Screenshots & Video**
https://www.loom.com/share/c77050e3bdac48c683af20ca0568e8f0?sid=fdd43f86-3bed-4cc0-9734-9073531af2b3
![Screenshot (403)](https://github.com/user-attachments/assets/6519705d-50dc-460d-86fb-45fd5502bea5)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 23H2

**Comment by brianp** [comment]
✅ Tested on Mac and *was not* able to reproduce the issue.
❌ Tested on Windows and *was* able to reproduce the issue.
✅ I was not also able to reproduce this on windows using dev versions.

So it could be auto-update related.

**Comment by MatthewHxlden** [comment]
I started mining this week using tari universe 1.2.17 and I have this same issue. Seed phrase is empty. 

<img width="755" height="102" alt="Image" src="https://github.com/user-attachments/assets/20612e02-4f1b-4bc4-b2b2-98dce8a5384c" />

<img width="756" height="180" alt="Image" src="https://github.com/user-attachments/assets/21297c4c-b9f1-428d-b1f0-9d71667b9270" />
