### ISSUE TITLE
Language doesn't translate on "Monero seed words"

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1160]
**Describe the bug**
When a user changed their language, "Monero seed words" didn't translated to the selected language. It stays in english.

**To Reproduce**
1. Go to settings 
2. Change the language under General settings
3. Click on wallet
4. See "Monero seed words" didn't translate

**Expected behavior**
When the user changes the language it should translate all over Tari Universe

**Screenshots**
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/06f2c0c6-e0e1-4509-a3f8-f7b54315795a">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version testnet v0.8.2

**Comment by brianp** [comment]
It's good to know, we need to update translations. But it's not a bug as long as there is some text that shows up. If placeholder text like `monero-seed-words` showed up instead I would consider it a bug.
