### ISSUE TITLE
V2:  Combined V2 Issues

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1168]
**Describe the bug**
Below is a list of issues seen

- Seeing a lot of `miner metrics` errors in the universe log
<img width="1236" alt="Screenshot 2024-12-02 at 1 02 20 PM" src="https://github.com/user-attachments/assets/2221af87-1100-4d21-a75a-05212dbf431a">
<img width="1236" alt="Screenshot 2024-12-02 at 1 04 02 PM(1)" src="https://github.com/user-attachments/assets/7d04a9fe-a63e-44d5-a778-782167996785">
- Unable to submit issue & logs:  Receive a 400 bad request error
<img width="1492" alt="Screenshot 2024-12-02 at 1 08 09 PM" src="https://github.com/user-attachments/assets/a927fe83-3dcf-487c-97b5-8fe752e453f1">
- I am sometimes unable to view my wallet balance (Usually when 0), if the CPU Power etc is at a loading state, my wallet balance is not displayed when I click on the eye icon
- When I initially switched to Ludicrous mode, my CPU Power was stuck on loading. A restart resolved this.
  - After discussing with Shannon, I switched my GPU Mining off and was thereafter able to switch between modes successfully (I did not have any GPU devices detected so my GPU Power was null)
<img width="1492" alt="Screenshot 2024-12-02 at 1 13 23 PM" src="https://github.com/user-attachments/assets/cf44c5ac-66c2-45e7-a9de-e98ab6935d30">
<img width="1236" alt="Screenshot 2024-12-02 at 1 13 19 PM" src="https://github.com/user-attachments/assets/72221683-fa18-4b6e-b0f8-712e08f698d8">
- I had the app running in the background for 30 minutes, when I brought it to the foreground, I saw that I had won rewards. Upon opening the rewards and checking them I noticed; after opening and closing the rewards section, my wallet balance stopped displaying and the miner animation was frozen
<img width="1492" alt="Screenshot 2024-12-02 at 2 47 06 PM(1)" src="https://github.com/user-attachments/assets/6e75369c-5411-4819-8905-f44e5f9be92e">
- When in the state above, when I tried to click opn `Stop Mining` I saw the below error:
<img width="1492" alt="Screenshot 2024-12-02 at 3 13 11 PM" src="https://github.com/user-attachments/assets/a86ea500-8237-4385-936c-2c946be6599c">

**Desktop (please complete the following information):**
 - MacBook Pro 2.3 GHz Dual-Core Intel Core i5
 - Venture 13.7.1

**Logs**
[com.tari.universe.beta.zip](https://github.com/user-attachments/files/17980460/com.tari.universe.beta.zip)

**Comment by Anziskavds** [comment]
- User is unable to log an issue on this build. They receive a 502 Bad Gateway error message.
- Copying or view seed words doesn't work. 
- User is unable to view their seed words and also unable to copy their seed words https://www.loom.com/share/cc06b36ceb4441b0aa303d511677a162
- Importing wallet gets stuck in a loading state https://www.loom.com/share/47e2482950944c7490fb6790dd394b85

**Comment by Misieq01** [comment]
### [ Linux ] => Ubuntu 24.04 | RTX 4080 Super | Ryzen 7800x3d
- Multiple miner_metrics warnings =>  **Not present | Couldn't reproduce** 
- Unable to submit issue and logs => **Not present | Couldn't reproduce** 
- Unable to view wallet balance when miners power are in loading state => **Not present | Couldn't reproduce** 
- Unable to switch modes when gpu is not detected and gpu mining is on => **Testing in progress** 
- Switching rewards view during win animation crashes wallet and animation => **Not present | Couldn't reproduce** 
- When in mentioned state, stoping mining display error snackbar => **Not present | Couldn't reproduce** 
- Copy or view seed words not working  => **Reproduced | Will work on it** 
- Importing wallet stuck on loading state =>  **Not present | Couldn't reproduce** 
---------

### [ Macos ] => Ventura 13.2.1 | Macbook Air 2020 | Apple M1
- Multiple miner_metrics warnings => **Testing in progress** 
- Unable to submit issue and logs => **Testing in progress** 
- Unable to view wallet balance when miners power are in loading state => **Testing in progress** 
- Unable to switch modes when gpu is not detected and gpu mining is on => **Testing in progress** 
- Switching rewards view during win animation crashes wallet and animation => **Testing in progress** 
- When in mentioned state, stoping mining display error snackbar => **Testing in progress** 
- Copy or view seed words not working  => **Testing in progress** 
- Importing wallet stuck on loading state => **Testing in progress** 
---------

### [ Windows ] => Windows 11 | RTX 4060 | Intel I5 - 12500H
- Multiple miner_metrics warnings => **Testing in progress** 
- Unable to submit issue and logs => **Testing in progress** 
- Unable to view wallet balance when miners power are in loading state => **Testing in progress** 
- Unable to switch modes when gpu is not detected and gpu mining is on => **Testing in progress** 
- Switching rewards view during win animation crashes wallet and animation => **Testing in progress** 
- When in mentioned state, stoping mining display error snackbar => **Testing in progress** 
- Copy or view seed words not working  => **Testing in progress** 
- Importing wallet stuck on loading state => **Testing in progress**

**Comment by Tas4tari** [comment]
I was able to see the frozen win animation when I won a block on 1203 on Windows 11. A restart resolved the issue
