### ISSUE TITLE
V2: Windows 11: Monero address: When i add in a new Monero address and click on Restart Now, the app closes but does not restart on its own

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1173]
**Describe the bug**
As a user I find when I go to Wallet and paste in a new Monero address, when I click on the `Restart Now` CTA within the modal, the app closes, however it does not restart on its own. When I restart the app, the Monero address I added in was saved successfully

**To Reproduce**
1. Go to 'tari universe'
2. Click on 'Settings' icon
3. Scroll down to 'Wallet'
4. Go to `Advanced`
5. Paste in a new Monero address
6. Modal should appear
7. Click on `Restart Now`

**Expected behavior**
App should close and restart immediately 

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 23H2

**App version**
- Beta build: 1203

**Comment by brianp** [comment]
Tested on the newest 0.8.5 Beta 1205 build. App restarts fine, but still loses focus on the restart. I consider this acceptable.

@Misieq01 could you also test this one on windows?

**Comment by Misieq01** [comment]
@brianp Hey I've made some improvements on my latest PR which includes shutdown, maybe they will improve it, will check
