### ISSUE TITLE
V2: User is unable to log an issue

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1174]
**Describe the bug**
the users receive a 502 Bas Gateway error message when the go to General settings to log an issue and the click on submit.

**To Reproduce**
1. Go to General settings
2. Log an issue
3. Click on submit
4. User receives a 502 Bad Gateway error message

**Expected behavior**
User should be able to log a issue without any errors

**Screenshots**
<img width="547" alt="image" src="https://github.com/user-attachments/assets/9fb942df-b04a-4aba-9d6e-b47599c8510f">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Beta Testnet v0.8.4

**Additional context**
[universe.log](https://github.com/user-attachments/files/18000718/universe.log)

**Comment by brianp** [comment]
We don't have domains etc setup for beta builds, so this feature only work on nextnet. Closing for now.
