### ISSUE TITLE
V2: Import wallet gets stuck on loading

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1176]
**Describe the bug**
Users gets stuck on loading state when they try to import another wallet by pasting the seed words.

**To Reproduce**
1. Go to wallet settings
2. Click on the edit button on seed words
3. Paste the other wallets you would like to import seed words
4. Users gets stuck on loading

**Expected behavior**
Users should be able to import a wallet successfully without getting stuck on loading

**Video**
https://www.loom.com/share/47e2482950944c7490fb6790dd394b85

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Tari Universe Beta v0.8.2

**Comment by shanimal08** [comment]
this is fixed in the beta builds >= v0.8.4(12/03)

**Comment by Misieq01** [comment]
I would need to test it again but yesterday I still had this issue on my linux

**Comment by brianp** [comment]
This worked great (very fast) on the current 0.8.5 Beta 1205 build.

@Misieq01 if you can verify on Linux please.

**Comment by Misieq01** [comment]
@brianp Working from what I see, just had issue that I mentioned after deleting wallet, fixed it and will include in my PR

**Comment by Anziskavds** [comment]
This is also no longer an issue for me on the Beta build v0.8.5.
[Tari Universe Beta v0.8.5.pdf](https://github.com/user-attachments/files/18054309/Tari.Universe.Beta.v0.8.5.pdf)
