### ISSUE TITLE
V2: Block time keeps running for more than 20min

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1177]
**Describe the bug**
Intermittently the block time keeps on running and doesn't expire/restart. I had a block time for more than 20min. I needed to close the app and reopen it to get the block time to reset and start again.

**To Reproduce**
1. Start the miner
2. Leave the miner to run
3. Block time keeps on running and doesn't expire/restart

**Expected behavior**
The block time shouldn't be running for longer than 10 min.

**Screenshots**
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/3045ce52-cfd7-43fa-ab31-a3f0df031cfd">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Tari Universe Beta v0.8.4

**Comment by brianp** [comment]
This is not true. The block timer can run for as long as it takes to get a block. There is *no* time limit on the block timer.
