### ISSUE TITLE
V2: Balance doesn't calculate correctly when a user won some tXTM

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1178]
**Describe the bug**
User was on a balance of 109.96 tXTM and they've won a block of 13.74 tXTM. The balance calculated to 137.44 tXTM where is should've been 123.7 tXTM.

**To Reproduce**
1. Keep the miner running until the user won a block
2. Calculate that amount to the users balance they had before they won a block
3. Currently it's not calculating correctly

**Expected behavior**
Balance should calculate correctly when the user has won a block

**Screenshots**
Before the win:
<img width="340" alt="image" src="https://github.com/user-attachments/assets/644802ed-a21c-48f9-a9e2-fabc37853958">

The amount the user won:
<img width="341" alt="image" src="https://github.com/user-attachments/assets/51d28485-28a0-4995-94f7-ac0e1ce03f27">

After the won:
<img width="361" alt="image" src="https://github.com/user-attachments/assets/80d6fbe2-38a2-4c0c-b337-efefe1e269a3">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Tari Universe Beta v0.8.4

**Comment by brianp** [comment]
Can you show the full history. It looks like you may have won 2 blocks.

**Comment by Anziskavds** [comment]
@brianp Apologies for this. You are correct I've won two block. I completely missed that. Sorry about that. I'm closing this issue because it' not an bug.
