### ISSUE TITLE
Add steps to resolve orphan chain wanring

### ISSUE THREAD

**Issue by brianp** [tari-project/universe#1193]
**Description**
Add an info icon with a tooltip:

Things to try:

- Check your Internet connection
- Wait 30 mins, sometimes the chain may need additional sync time, or a re-org is happening
- Restart the app
- Try using a Tor Bridge (in Settings)
- Try disabling Tor (in Settings)
- Try an app reset (in Settings)

**Comment by metalaureate** [comment]
changed order:

Things to try:
1. Check your Internet connection
2. Wait 30 mins
3. Restart the app
4. Try using a Tor Bridge (in Settings)
5. Try disabling Tor (in Settings)
6. Try an app reset (in Settings)

**Comment by brianp** [comment]
Fixed with https://github.com/tari-project/universe/pull/1213
