### ISSUE TITLE
Changing to custom mode gets the user stuck on loading

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1199]
**Describe the bug**
When a user change their mode to custom mode and they apply the changes, they get stuck in a loading state.

**To Reproduce**
1. Go to mode
2. Click on custom
3. Apply changes
4. Save changes
5. user gets stuck on a loading state

**Expected behavior**
User should be able to change their mode to custom without getting stuck on loading.

**Screenshots**
<img width="383" alt="image" src="https://github.com/user-attachments/assets/b491c2c4-14ed-45a6-b4f6-fed69b6aa7d1">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Tari Universe Testnet v0.8.7

**Comment by shanimal08** [comment]
@Anziskavds is this still happening regularly, and how long were you stuck? 😅 

i just checked 0.8.7 and it only loaded for a couple of seconds for me when switching between modes and custom

**Comment by Anziskavds** [comment]
@shanimal08 This is no longer an issue on Mac on Testnet v0.8.7.
