### ISSUE TITLE
Release Notes doesn't translate when the user changes their language

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1201]
**Describe the bug**
When a user changes their language "Release Notes" doesn't translate.

**To Reproduce**
1. Go to General settings
2. Change the language
3. See that "Release Notes" doesn't translate to the language

**Expected behavior**
When a user changes their language, it should translate all over the app

**Screenshots**
<img width="512" alt="image" src="https://github.com/user-attachments/assets/25939c08-f48b-492f-97dc-df69f86f917b">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Testnet v0.8.7

**Comment by brianp** [comment]
Language translations aren't considered bugs and get updated periodically.
