### ISSUE TITLE
0.8.7: Pool Mining When I have disabled Pool Mining, when the app restarts and I go back to re-enable Pool Mining, when I click on the toggle to enable it, the modal closed and the user is back on the miner screen, with just the mining visual visible

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1208]
**Describe the bug**
As a user when I have disabled Pool Mining, once the app restarts and I go back to enable Pool Mining, I find that when I click on the toggle to enable it, the modal closes and the user is back on the miner screen with just the visual mode of the block animation displayed. When I try to close the app by clicking on the `X` icon I am unable to. If I try to force quit I am unable to. 
I have to go to Resource monitor and end the processes in order for the app to close

When I restart the app, I see that Pool Mining has been enabled

**To Reproduce**
1. Go to 'tari universe'
2. Click on 'Settings' icon
3. Scroll down to and click on 'Pool Mining'
4. Disable Pool mining
5. Click on `Restart Now` on the modal that appears
6. App should restart successfully
7. Click on `Settings`' icon
8. Scroll down to and click on 'Pool Mining'
9. Click on the toggle to enable Pool Mining
10. Observe

**Expected behavior**
User should see the restart modal appear asking the user to restart. When the user clicks on `Restart Now` the app should restart successfully

**Screenshots**
https://www.loom.com/share/03a584c437104b14b7415fd0815d381b?sid=fc606ab3-7b72-40d0-9244-9347c951a23d

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11

**Logs:** 
[logs.zip](https://github.com/user-attachments/files/18037237/logs.zip)

**Comment by Tas4tari** [comment]
Fixed here: https://github.com/tari-project/universe/pull/1207

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.8.8 and issue is still prevalent

**Comment by Tas4tari** [comment]
[logs.zip](https://github.com/user-attachments/files/18078113/logs.zip)

**Comment by Anziskavds** [comment]
This is also an issue on a MacBook Air M1 2020 on Testnet v0.8.8

**Comment by Anziskavds** [comment]
This is also an issue on a MacBook Air M1 2020 on Testnet v0.8.9 
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/962f47e7-82de-4f9e-adce-603261980bb0">

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.8.9 and issue is still prevalent

**Comment by mmrrnn** [comment]
Solved this issue: https://github.com/tari-project/universe/pull/1228

**Comment by Anziskavds** [comment]
Issue is still happening for me on a MacBook Air M1 2020 13 inch Sequoia 15.1.1 on Testnet v0.8.13

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.8.13 and issue is still prevalent

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.8.25. This is no longer an issue as I see the restart now pop up.
However, when I click on `Restart Now`, the app just closes and does not restart. When I manually restart I can confirm that Pool Mining is enabled once again. I will create a new ticket for this
