### ISSUE TITLE
I rebooted my pc and the miner did not auto-restart

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#122]
**Describe the bug**
Restart on reboot if app was running.

**Comment by stringhandler** [comment]
Add a setting "Start Tari Universe when I log on"

**Comment by stringhandler** [comment]
![Image](https://github.com/user-attachments/assets/ba70a42b-2b9e-4082-af52-b717fc48891b)
Maybe something like this?

**Comment by Misieq01** [comment]
Resolved in pull request => #531
