### ISSUE TITLE
Don't let me install TU on a machine/OS that is too old

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#123]
**Describe the bug**
E.g. Big Sur might be too old because the webGL animations don't render on my machine (although they do on Lusion's demo).

**Comment by stringhandler** [comment]
Need more info: What is too old?

**Comment by mmrrnn** [comment]
Duplicate of [#193](https://github.com/tari-project/universe/issues/193)?

**Comment by brianp** [comment]
Closing as won't fix. Maybe resolved with #193 maybe not. It'll resurface if it's an issue.
