### ISSUE TITLE
0.8.11: Windows: When restarting the app I get stuck at 30% (Checking for latest version of sha-p2pool)

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1231]
**Describe the bug**
As a user I was testing ending the minotari processes on Task Manager and confirming they restart immediately. I'd noticed that one of the minotari processes did not restart immediately so I wanted to confirm. I then closed the app, waited for all processes to end within Resource Monitor and then I opened the Tari Universe app.
When the app was opened, on start up & initialization the app gets stuck at 30% `Checking for latest version of sha-p2pool`
I tried restarting the app to get out of this state but was unable to
I also noticed that there were no logs visible

**To Reproduce**
Pre-conditions:
- Tari Universe app should be installed
- User should have the app running

1. Go to 'Task Manager'
2. Click on 'Apps'
3. Scroll down to 'minotari processes'
4. Click on all minotari processes and `End task`
5. All minotari processes should restart immediately after being ended
6. In this case minotari_merge_mining_proxy (blue icon) did not restart
7. Close the app
8. Go to resource monitor and confirm all tari, minotari, tauri, gpu miner processes have ended
9. Go to and click on the app icon to open the app
10. Observe 

**Expected behavior**
User should see the app open and start up with no issues. Logs should also be visible to the user

**Screenshots**
![Screenshot (461)](https://github.com/user-attachments/assets/79b8fa78-81f5-4861-ab20-949115fdd794)
![Screenshot 2024-12-11 144100](https://github.com/user-attachments/assets/81057924-4950-4b83-b3c4-e6223a4e9fbc)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 23H2

**Comment by Tas4tari** [comment]
[gpuminer.zip](https://github.com/user-attachments/files/18095912/gpuminer.zip)

**Comment by Tas4tari** [comment]
After 30+ minutes, the app started, however I still do not see any logs:
![Screenshot 2024-12-11 154510](https://github.com/user-attachments/assets/94534cf7-c59e-4bdb-94b6-08bfd26bc798)

**Comment by Tas4tari** [comment]
When stuck at 30% this is what I see in the Universe logs
![Screenshot (467)](https://github.com/user-attachments/assets/572c901c-646e-4366-bb91-603cc9fa4bed)

**Comment by Tas4tari** [comment]
Issue also came up when I imported a wallet, errors seen for minotari node as well
![Screenshot (468)](https://github.com/user-attachments/assets/417422aa-d455-4a26-9fac-49041dbfa78e)

**Comment by Tas4tari** [comment]
[logs.zip](https://github.com/user-attachments/files/18097976/logs.zip)

**Comment by Yattilla** [comment]
I have the same issue

**Comment by brianp** [comment]
Should be fixed on https://github.com/tari-project/universe/pull/1276
