### ISSUE TITLE
CPU Power dropped quite a lot on ECO mode on 0.8.9 from what it was on v0.8.8 

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1233]
**Describe the bug**
My CPU Power dropped quite a lot on ECO mode on 0.8.9 from what it was on v0.8.8.

**To Reproduce**
1. Check CPU Power on current build
2. Install new build
3. Check your CPU Power again
4. Compare the two with each other. My cpu dropped quite a lot on the new build than what is was on the previous build

**Expected behavior**
CPU Power should stay relatively the same between builds

**Desktop (please complete the following information):**
 - OS & Version: Macbook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version [e.g. chrome v71.0.12345]

**Additional context**
0.8.8 | 11/12/2024 | gh2jo^OWd1@0V%UDxsfd | Macbook Air M1 2020 | ECO | 702.41
0.8.9 | 11/12/2024 | #nJ&N1opIS1quPV4pvln | Macbook Air M1 2020 | ECO | 388.39
https://docs.google.com/spreadsheets/d/1bApqsTHl59upGi8WI3jKzTojNcCjOFCPIEMJxQbEfwM/edit?gid=0#gid=0

**Comment by brianp** [comment]
Noted. As we've moved on from these versions. Closing this issue for now.

**Comment by brianp** [comment]
Please open a new one. v0.8.9 doesn't matter anymore. But a significant drop on 0.8.25 does.

Also we're going to have to learn about thresholds. The numbers won't always be the same there's a lot of things that matter like what else you're running on your system etc. And unless we have a scientific example. We're going to see significant variance. And it doesn't make it a bug. Hence the spreadsheet. We do want to track over time, but it doesn't mean there's a bug. There could be. But we're going to end up in a place where you open tickets constantly and I close them constantly.
