### ISSUE TITLE
0.8.13: Pool Mining Stats not visible

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#1240]
**Describe the bug**
I find when I go to the Pool Mining settings, the Pool Mining stats are not visible. There are no connected peers or any information for 

- Listener addresses
- Network info
- SHA3 Stats
- RandomX Stats

**To Reproduce**
**Pre-conditions:**

- User should have Tari Universe installed
- User should have the app open and mining
- Pool mining should be enabled

**Steps to reproduce the behavior:**
1. Go to 'Settings'
2. Click on 'Pool Mining'
3. Scroll down to 'Pool Mining Stats'
4. View stats

**Expected behavior**
When Pool Mining is enabled, user should see stats visible

**Screenshots**
![Screenshot (471)](https://github.com/user-attachments/assets/6613909d-0da2-4807-8fbd-e09cfa5cb1da)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 23H2

**Additional context**

**Comment by brianp** [comment]
Heads up that this can take up to 30m to populate.

**Comment by Tas4tari** [comment]
Thanks @brianp I was unaware of that. Will check and confirm

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.8.14 and I am able to view Pool Mining stats:
![Screenshot (501)](https://github.com/user-attachments/assets/1abe30a8-3745-4d1a-9e87-abc4211f75bc)
