### ISSUE TITLE
Users are unable to connect to Airdrop

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1254]
**Describe the bug**
When a user tries to connect to Airdrop nothing happens. The user should be able to connect to Airdrop when the click the Aplly Invite code button but when they get redirected to Airdrop the user is logged in with X but the airdrop account doesn't connect with Tari Universe.

**To Reproduce**
1. Go to Airdrop settings
2. Click on the Apply Invite code button
3. User should redirect to Airdrop
4. User should go back to Tari universe
5. User should connect to Airdrop but currently they are unable to connect their Airdrop account

**Expected behavior**
User should have their Airdrop account connected when they click on the Apply invite code button and they are logged in with X

**Video**
https://www.loom.com/share/abd00192b6354f16a94b2ec07af031f0

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Tari Universe Testnet v0.8.14

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.8.14 and see slightly different behavior:
- When I click on `Apply code` I am taken to the `airdrop.tari.om/auth` screen, however it is initially blurred out. When I do a hard refresh I see the following:
![Screenshot (484)](https://github.com/user-attachments/assets/928a28a6-033d-44ed-b9e4-37b50bc06889)

After another refresh, I am able to click on the `Prove you're not a robot` verification and I can proceed to the twitter auth. When I get to the twitter Auth screen:
https://x.com/i/flow/login?authenticity_token=1c191b183d6f2c9e343ceb68aae183ebac44b176&redirect_after_login=https%3A%2F%2Fapi.x.com%2Foauth%2Fauthenticate%3Foauth_token%3DqmVlLwAAAAABm3RQAAABk77TL-I
I find that it constantly loads witha 400 bd request error. The screen does not load so I can enter my username & password to log in:
![Screenshot (486)](https://github.com/user-attachments/assets/ae5f9ceb-95b7-40fe-9bbd-8331d5909455)
![Screenshot (487)](https://github.com/user-attachments/assets/51817ff1-4e2b-4cd2-b120-a9ce36c1642a)
![Screenshot (488)](https://github.com/user-attachments/assets/17aad352-299c-45bb-9bdd-ab4dd399ec88)
![Screenshot (489)](https://github.com/user-attachments/assets/5c6b9640-d469-47f1-86d2-4db32aa9b6d0)
![Screenshot (490)](https://github.com/user-attachments/assets/c592e99f-b69b-4f92-8f8a-37ef326aa5c3)



When I go back to the app, and click on the `Apply code` to try again, I am taken to the ffg screen on Twitter:
https://x.com/i/flow/login?authenticity_token=1c191b183d6f2c9e343ceb68aae183ebac44b176&redirect_after_login=https%3A%2F%2Fapi.x.com%2Foauth%2Fauthenticate%3Foauth_token%3Dn-SHkgAAAAABm3RQAAABk77rx6M
![Screenshot (491)](https://github.com/user-attachments/assets/83257970-790f-4472-b668-ddedc2420ca1)

**Comment by Tas4tari** [comment]
After my 3rd attempt I was able to connect successfully on 0.8.14
![Screenshot (498)](https://github.com/user-attachments/assets/4bebf424-8761-4677-96f1-b0041741e1f1)

**Comment by brianp** [comment]
This was a yat connection problem i believe has been resolved.

**Comment by Tas4tari** [comment]
I have not seen this issue occur in weeks whilst testing on Windows
