### ISSUE TITLE
ERROR minotari_node is not healthy. Health check returned false

### ISSUE THREAD

**Issue by gabrieloshiro** [tari-project/universe#1273]
**Describe the bug**
Tari Universe was running properly up until yesterday (2024-12-15). Now the app loops with logs

```
12:42:33 INFO  Launching minotari_node node
12:42:37 ERROR minotari_node is not healthy. Health check returned false
12:42:37 WARN  minotari_node is not healthy. Waiting for startup time to elapse
12:42:42 ERROR minotari_node is not healthy. Health check returned false
12:42:42 WARN  minotari_node is not healthy. Waiting for startup time to elapse
12:42:47 ERROR minotari_node is not healthy. Health check returned false
12:42:47 WARN  minotari_node is not healthy. Waiting for startup time to elapse
12:42:55 ERROR minotari_node is not healthy. Health check returned false
12:42:55 INFO  Stopping minotari_node node with exit code: 0
12:42:55 INFO  minotari_node exited successfully
12:42:56 WARN  Restarting minotari_node after health check failure
```

in UI it is stuck on 30% (see screenshot below)

**To Reproduce**

1 On linux  terminal `./Tari.Universe_0.8.24_amd64.AppImage`

**Expected behavior**
The app launches and starts mining.

**Screenshots**
![image](https://github.com/user-attachments/assets/b86b8659-5b40-458b-94a3-a284ef21065e)

**Desktop (please complete the following information):**
 - OS & Version: Linux 6.8.0-51-generic

**Comment by brianp** [comment]
Hey! Thanks for posting. We are aware of this issue and plan to roll out a fix.
