### ISSUE TITLE
User gets logged in on another users Airdrop account

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#1282]
**Describe the bug**
My Airdrop account was disconnected and when I clicked on the "Apply Invite code" button I received the success screen but I am logged in on another users Airdrop account. This is not my username for X/Twitter. Please see video below.

**To Reproduce**
1. Go to Airdrop settings
2. Click on "Apply invite code"
3. User receives a success screen on Airdrop
4. User is logged in on Airdrop but not with their own Twitter/X account

**Expected behavior**
User should get logged in on Airdrop with their own existing account.

**Video & Screenshot**
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/12967d71-2e31-4fde-82fb-d122e0945b94" />
https://www.loom.com/share/3194d4de19f64ba6abcddc7a17e986cb

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 13 inch Sequoia 15.1.1
 - Browser & Version Alpha v0.8.25

**Comment by BalazsSevecsek** [comment]
couldn't reproduce it with 2 twitter accounts

**Comment by Anziskavds** [comment]
Please reopen this ticket because the issue is still happening on Alpha v0.8.27 cc @BalazsSevecsek @brianp @stringhandler
