### ISSUE TITLE
v0.1.37 During auto-update, the Ready to Restart popup is dismissed without any user actions

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#129]
**Describe the bug**

**To Reproduce**
1. Have an older version of Tari Universe installed
2. Open the Tari Universe application (if it is already open, close it and re-open)
3. You should see the New Version of Tari Universe is available popup - click Yes
4. The tari Universe app will open with a popup that says Ready to Restart
5. After a second or two, the modal will close and the app closes along with it without the user selecting "yes" or "no".

Video: 
https://www.loom.com/share/0376a28b68c8473aa757e4e379f24167?sid=02fafdf8-f4dc-4d01-873b-646784e090e8

**Expected behavior**
The user should be able to click yes if they want to restart the app or no if they do not want to. 

**Screenshots**
![Screenshot 2024-08-23 at 3 37 34 PM](https://github.com/user-attachments/assets/b5b23fd8-3217-44e5-8915-1bb24a1e27a6)

**Desktop (please complete the following information):**
 - OS & Version: Mac M1 Sonoma 14.6.1

**Comment by stringhandler** [comment]
Closing because we have new UI
