### ISSUE TITLE
Downloading the .msi install file with out of the box Microsoft Edge is problematic

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#130]
**Describe the bug**
When downloading the Tari Universe .msi file with Edge browser, the download is marked not safe. The user must use a workaround to get the downloaded file to be clickable. 

**To Reproduce**
Captured in the video:
https://www.loom.com/share/c2e6d874402a4f4e9b9733dd0f4309d5?sid=ae4483da-4a22-4813-a341-54c08bed0519

**Desktop (please complete the following information):**
 - OS & Version: Windows 11 Home build 22631.4037
 - Browser & Version:  Edge 127.0.2651.105

**Comment by stringhandler** [comment]
this and #131 seem to be the same issue

**Comment by leet4tari** [comment]
I think this is the Edge Browser noting that the download might be a problem, more related to malware and the Edge Browser trying to be secure. Might be better when the installer and binaries inside are signed with a reputable certificate.
