### ISSUE TITLE
Minotari node requires VS redist

### ISSUE THREAD

**Issue by ghost** [tari-project/universe#132]
**Describe the bug**
After using the workaround to the bug here: https://github.com/tari-project/universe/issues/131 , I got the Tari Universe app to install but running it was blocked by an error. It was never able to start. 

**To Reproduce**
See the workaround for issue https://github.com/tari-project/universe/issues/131 . I had to use the workaround to get to the point where Tari Universe was installed and trying to Complete is own download prior to mining. 

I got this error after the app opened and tried to start its initialization: 
![Screenshot 2024-08-23 at 5 22 40 PM](https://github.com/user-attachments/assets/eaa47098-c6b5-47a0-8b4d-62270e7b9052)

**Desktop (please complete the following information):**
 - OS & Version: Windows 11 Home
 - Browser & Version: Edge

**Comment by leet4tari** [comment]
@Cultmojo if you download and install the ```Microsoft Visual C++ Redistributable``` from https://aka.ms/vs/17/release/vc_redist.x64.exe and restart the app, does it solve the problem?

**Comment by Cultmojo** [comment]
@leet4tari  That does solve the install issue.

**Comment by leet4tari** [comment]
After trying to bundle the ```Microsoft Visual C++ Redistributable``` and running into a number of install problems, I think it might be easier and possible better, to do an register check if the VC redistributable is installed, and if not, open a dialog/popup that will have the link to download and install, instead of failing.
```
Key="SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\X64"
Name="Installed"
Value="1"
```
<img width="1621" alt="Screenshot 2024-08-29 at 10 57 28" src="https://github.com/user-attachments/assets/83aebfc2-441c-4668-b1f0-3c93622480a5">
<img width="1621" alt="Screenshot 2024-08-29 at 10 58 40" src="https://github.com/user-attachments/assets/cdd11b7b-1e66-462b-aa5a-fdbcc7e3dd85">

**Comment by uforiaio** [comment]
If the installer can query wmic to see if vc++ redist is installed or not, it would make it easier to validate the dependencies. If the vc++ versions are added to experimental "versions" it may be helpful. If it is not detected, have an info dialogue to download them via a link within Tari. 

![image](https://github.com/user-attachments/assets/0c48ce3b-3425-4bd7-bc01-cd318d2fd825)


`wmic product where "Name like '%%Visual C++%%'" get Name, Version`

Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.40.33810     14.40.33810
Microsoft Visual C++ 2022 X86 Additional Runtime - 14.40.33810  14.40.33810
Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.40.33810     14.40.33810
Microsoft Visual C++ 2022 X64 Additional Runtime - 14.40.33810  14.40.33810

**Comment by leet4tari** [comment]
Some corner cases covered #750 , still a little bit of work to complete.

**Comment by brianp** [comment]
Closing as I believe this issue is mostly solved by the required dependencies modal for windows. Feel free to comment or re-open if issues remain.

**Comment by uforiaio** [comment]
It was early October, it's been fixed from what I experienced and what the
common questions/complaints were on TG. Thanks!
