### ISSUE TITLE
v0.1.37 Horizontal scroll bar on Windows

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#149]
**Describe the bug**
A horizontal scroll bar appears on Windows. 
![image](https://github.com/user-attachments/assets/ca080739-512a-42f0-9e08-e411542f3ab9)

**Comment by stringhandler** [comment]
Reopened in v0.2.0


![Image](https://github.com/user-attachments/assets/1f74253a-93d6-4b4c-9aaa-2fdbd9197af9)

**Comment by mmrrnn** [comment]
I'm not able to reproduce it now. Tried to play with it, also asked Bartek to open on his computer without result.


![Image](https://github.com/user-attachments/assets/a4f916c8-f83f-4ab0-a40e-4a8de5973940)

**Comment by stringhandler** [comment]
cool, let's close it
