### ISSUE TITLE
Enforce minimum screen size

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#170]
**Describe the bug**
Nck: Is there a minimal screen resolution required for the app? I tested on 1280x800 and it wasn't scaling properly.
Shan: we should add a min cos the block tower gets quite nasty
![image](https://github.com/user-attachments/assets/80b6e4d1-2623-41ad-be0d-a3af36e911f7)

**Expected behavior**
Not nasty on various monitor sizes.

Laptop Resolutions:

- 1920x1080 (Full HD) - Common in 13 to 15.6-inch laptops.
- 2560x1600 (WQXGA) - Found in 13 to 14-inch high-end laptops, especially those with a 16:10 aspect ratio.
- 1366x768 - Still seen in budget laptops, particularly smaller ones around 11 to 14 inches.
- 2880x1800 (Retina Display) - Common in 13 to 16-inch MacBook Pros.
- 3840x2160 (4K UHD) - Found in some 15 to 17-inch premium laptops, especially those aimed at creative professionals.
Desktop Monitor Resolutions:
- 1920x1080 (Full HD) - The most common resolution for 21.5 to 27-inch monitors, particularly in budget to mid-range options.
- 2560x1440 (QHD) - Popular in 24 to 27-inch monitors, especially among professionals and gamers who need more screen real estate and clarity.
- 3840x2160 (4K UHD) - Found in 27-inch and larger monitors, favored by users needing high detail and large workspace.
- 1600x900 - Occasionally found in smaller desktop monitors around 19 to 21.5 inches, though less common today.
- 1920x1200 (WUXGA) - Found in some 24-inch monitors, especially those used in professional settings where a 16:10 aspect ratio is preferred.

**Comment by stringhandler** [comment]
@shanimal08  please confirm. I think we've already done this

**Comment by shanimal08** [comment]
@stringhandler we only set min width and height ([997 and 620](https://github.com/tari-project/universe/blob/main/src-tauri/tauri.conf.json#L56C1-L57C34) respectively), i think before this ticket was created

didn't use the resolutions mentioned in the description. i'm not 100% sure if we can changes those values in the tauri config based on the machine, will check though

@metalaureate can we just do a standard min width/height or does it have to be machine specific? 😬

**Comment by metalaureate** [comment]
Agreed
