### ISSUE TITLE
Staged Seed Phrase Handling

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#184]
As a user, before mainnet launch I need Tari Universe to facilitate my adhering to Tari recommendations for seed phrase handling: https://rfc.tari.com/RFC-0153_StagedWalletSecurity?highlight=stage#a-staged-approach

**Comment by stringhandler** [comment]
Notified designers

**Comment by brianp** [comment]
Will re-open this when it becomes relevant again. I'm sure we'll need it but if it's not in the immediate list of priorities then we can push for now.
