### ISSUE TITLE
During Auto-update, when app asks if user wants a restart, no action causes a forced quit 

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#196]
**Describe the bug**
During the auto-update, the app will ask if the user wants to restart. If the user does nothing for only a couple seconds (does not click "Yes" or "No") the app will close - a forced quit. When the app is opened after the forced quit, it is updated to the latest version. No functional bug but a harsh user experience. 

![Screenshot 2024-08-27 at 4 20 22 PM](https://github.com/user-attachments/assets/66ff05d3-dd5d-4de7-a5b2-ca7136770d58)

**To Reproduce**
See video of the workflow with audio walkthrough:
https://www.loom.com/share/437c1e3edeef470b8bdc17fbfe2decf4?sid=9932c59c-9c7d-485a-8d13-93f611f6d70f

**Expected behavior**
Not sure if this is desired behavior or not. Should we wait for the user to make a choice or force quit? One thing to consider is when the user selects "Yes" the restart closes the app and automatically re-opens. A very smooth user experience. However, when it is forced-quit due to inaction, it is merely closed. Seems like a harsh user experience given it doesn't give the user much time to make a decision and it doesn't re-open the app for the user. 

**Desktop (please complete the following information):**
 - OS & Version: MacBook Pro M1 14.6.1

**Comment by stringhandler** [comment]
Blocked until we decide whether to show our own auto update UI or keep using tauri's

**Comment by stringhandler** [comment]
closed because we have new ui
