### ISSUE TITLE
App About modal needs key information

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#212]
**Describe the bug**

Currently:
<img width="289" alt="Screenshot 2024-08-28 at 2 47 18 PM" src="https://github.com/user-attachments/assets/5de17619-f0c5-43f4-94a0-3211e77dc029">

Use Postman as template:
![image](https://github.com/user-attachments/assets/9cf4b0b0-91aa-456e-9042-ec9053b29e6c)

Link to "License": https://github.com/tari-project/tari-universe/blob/main/LICENSE.md
	
Add: Copyright (c) 2024  Tari Labs, LLC

**Comment by MCozhusheck** [comment]
![Image](https://github.com/user-attachments/assets/ff6c53c1-e066-404d-bf18-926090f399a4)

**Comment by MCozhusheck** [comment]
Tried filling fields in `tauri.conf.json` described in https://tauri.app/v1/api/config/#bundleconfig but unfortunately I couldn't managed to include a link to the license

**Comment by MCozhusheck** [comment]
Not even programmatically helps in this case to include a link to the license
