### ISSUE TITLE
Auto Update needs to be one step not two

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#213]
**Describe the bug**
Currently auto update asks you to 1) Download and then 2) Restart but it should be all one step.

**Comment by mmrrnn** [comment]
What os, universe app version did you use?


https://github.com/user-attachments/assets/a451ef7c-805a-41be-b84b-54304d4397ed

**Comment by metalaureate** [comment]
Mac Sonoma M1 doesn't restart after this screen.

<img width="1351" alt="Screenshot 2024-09-04 at 7 26 54 AM" src="https://github.com/user-attachments/assets/35275433-fcb5-4917-bd56-7ba906c45cca">
