### ISSUE TITLE
Add Semver compatibility for downloaded binaries

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#244]
For xmrig, tari, p2pool and gpu miner, we must specify a set of versions that are acceptable. These must be compiled into the rust and must only be changed via a new version of Tari Universe.

The rules should be the same as those used for cargo.toml.

E.g.

```json
/// perhaps in binary_versions.json
{ 
   "xmrig" : "6.22.0",
   "minotari_node": "1.3.0-pre.0",
   "minotari_mmproxy": "1.3.0-pre.0"
}
```

IMPORTANT: If a version exists that is higher than the rule in `binary_versions`, then it must be logged that a new version was found, but it is keeping the existing version.

Please include a unit test for this.

**Comment by Misieq01** [comment]
Resolved in pull request => #259
