### ISSUE TITLE
Add a log message when Tari universe shuts down so that we can see if it shut down cleanly

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#247]

**Comment by karczuRF** [comment]
As I see we have some logs already. What kind of log msg should be added?


![Image](https://github.com/user-attachments/assets/24c3ead8-7504-4636-ac34-b1a6c6b91c32)

**Comment by stringhandler** [comment]
Please add "Tari Universe v0.2.0 shut down successfully"
