### ISSUE TITLE
Can we get deep linking to work on Tauri V1 app?

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#274]
We need to support deep linking for app referal and other marketing related use-cases. They are not officially supported in V1:

https://v2.tauri.app/plugin/deep-linking/

but there are plugins for Tauri v1 apps:
https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/deep-link

Can we explore making this work? We need to pass a referral code via a deep link from a webpage to open the app and be able to then handle the response in the UI.

**Comment by stringhandler** [comment]
Putting it in milestone 0.2 for now, but it's only due for 0.3. We should start investigating now though
