### ISSUE TITLE
p2pool is stuck at 75% on 0.2.2 Mac

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#292]
**Describe the bug**
Installing manually with a prior 0,1.39 build. Been here for 5 minutes:

<img width="1369" alt="Screenshot 2024-09-04 at 8 56 18 AM" src="https://github.com/user-attachments/assets/a407899a-c593-4200-87d8-a05bd52ea926">

The problem went away after building the app locally, closing, and then re-starting the 0.2.2 release.

**Comment by stringhandler** [comment]
No longer a problem
