### ISSUE TITLE
v0.2.5 no GPU with spinner in GPU panel

### ISSUE THREAD

**Issue by leet4tari** [tari-project/universe#322]
Running a computer without a GPU, has the GPU panel showing a spinner, which would be confusing for a user.

**Expected behavior**
Thinking greying out the panel when there is no GPU, might be an idea

**Screenshots**
<img width="1621" alt="Screenshot 2024-09-06 at 12 13 48" src="https://github.com/user-attachments/assets/1fed9c1a-c1af-4f10-832f-89e5c858ce9a">

**Desktop (please complete the following information):**
 - Windows 11 - v0.2.5

**Comment by stringhandler** [comment]
Similar to #358
