### ISSUE TITLE
[0.2.5 Windows] Cannot update or paste Monero address

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/universe#324]
**Describe the bug**
Cannot update or paste Monero address

**To Reproduce**
1. Open settings
2. Select Monero address, delete it
3. Try to paste or type maually

**Expected behavior**
It should be update-able

**Screenshots**

**Desktop (please complete the following information):**
 - Windows Pro 11

**Comment by stringhandler** [comment]
You can also remove the Submit and Cancel buttons here
