### ISSUE TITLE
[0.2.5 Windows] Changing mode while mining gets stuck or unresponsive

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/universe#327]
**Describe the bug**
Changing mode while mining gets stuck

**To Reproduce**
1. Start mining with _Ludicrous_ mode
2. Change the mode

![image](https://github.com/user-attachments/assets/16e150ee-a9ae-4d0b-a636-e8c701d7ad2b)

**Expected behavior**
Gettign stuck in _Ludicrous_ mode should not happen.

**Desktop (please complete the following information):**
 - Windows 11 Pro

**Comment by stringhandler** [comment]
Fixed in 0.2.7. Happy to reopen if not the case
