### ISSUE TITLE
[0.2.5 Windows] Pause mining does not work

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/universe#329]
**Describe the bug**
Pause mining does not work.

![image](https://github.com/user-attachments/assets/5dd81ddf-5cca-4646-b5bc-3b53003b290b)

**To Reproduce**
1. Start mining
2. Pause mining

**Expected behavior**
Pause mining should work.

**Desktop (please complete the following information):**
 - Windows 11 Pro

**Comment by stringhandler** [comment]
fixed in 0.2.7
