### ISSUE TITLE
v0.2.7 Clicking the Pause Mining button rapidly can get the miner stuck in the pause state

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#338]
**Describe the bug**
When the user clicks the pause mining button and then clicks the start mining immediately after it enables, the miner can get stuck in the pause state.

**To Reproduce**
1. Start mining
2. Click on the "pause mining" button
3. As soon as the start mining button enables, click it
4. The miner gets stuck in the pasued state
5. To get unstuck, just click the pause mining button and then the Start mining button. 
https://www.loom.com/share/3fb4112202674b2480f001327db8e77e?sid=036fd9ec-ca14-4b07-9979-eda5abf1e1e3

**Desktop (please complete the following information):**
 - OS & Version: Mac M1 Sonoma 14.6.1

**Comment by stringhandler** [comment]
Potentially fixed in 0.2.8
