### ISSUE TITLE
Don't start p2pool if it's disabled

### ISSUE THREAD

**Issue by shanimal08** [tari-project/universe#368]
**Describe the bug**
got stuck at 75% starting P2Pool

**To Reproduce**

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/e7ff5605-ff7e-49ca-b8ab-d3be53d59273)

**Desktop (please complete the following information):**
 - OS & Version: [e.g. iOS 10.2.1]
 - Browser & Version [e.g. chrome v71.0.12345]

**Smartphone (please complete the following information):**
 - Browser & Version [e.g. stock browser v0.1.2]

**Additional context**

**Comment by stringhandler** [comment]
duplicate
