### ISSUE TITLE
v0.2.7 Application will not fully sync/start

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#375]
Describe the bug
The application gets stuck at 75% "Starting P2Pool" and will not progress/start. No amount of time will allow the app to finish syncing. It's stuck at 75%.

<img width="1219" alt="Screenshot 2024-09-09 at 2 32 40 PM" src="https://github.com/user-attachments/assets/58a90552-63a4-4a7c-a95f-7031858adb6e">

**Comment by stringhandler** [comment]
duplicate #368
