### ISSUE TITLE
v0.2.7 Tari Universe will not sync/start

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#376]
**Describe the bug**
The application gets stuck at 75% "Starting P2Pool" and will not progress/start. No amount of time will allow the app to finish syncing. It's stuck at 75%. 

<img width="1324" alt="Screenshot 2024-09-09 at 2 09 55 PM" src="https://github.com/user-attachments/assets/3a99292b-d874-4c16-86f8-e09a720a00cf">

**Smartphone (please complete the following information):**
 - Device: Mac M1 Sonoma 14.6.1

**Comment by stringhandler** [comment]
I think this may be fixed in 0.2.8
