### ISSUE TITLE
v0.2.8 Wallet balance is missing 

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#378]
**Describe the bug**
I had > 1.9m txM in earlier version. After update to 0.2.8, my balance is zero. 
<img width="505" alt="Screenshot 2024-09-09 at 3 04 57 PM" src="https://github.com/user-attachments/assets/a72a46a6-22a3-406f-a8ad-d0ba123f297e">

**To Reproduce**
1. Update wallet to 0.2.8 from earleir version. Must have a balance. 

Wallet Address: f2GZEnXF8JGjvPe9NuRtnX1gVxBETQLnv6X6JJ5JvGnVQB7SVFCU82TRvFY1rEKJQ9cGprxRiDoSYJXsBbQRLTCaFzk
Wallet seed words:
theory panda copy head seat fork hand paddle catalog unlock slam cousin sting valley mixture inspire flavor pluck attend unknown approve client target camera

Logs:
[Archive 2.zip](https://github.com/user-attachments/files/16935382/Archive.2.zip)

**Expected behavior**
The wallet balance should persist after updating to new versions.

**Desktop (please complete the following information):**
 - OS & Version: Mac Sonoma 14.6.1

**Comment by mmrrnn** [comment]
Tari Universe on Windows v0.2.1(before update):
![Image](https://github.com/user-attachments/assets/55c6523a-7f8c-4ad9-abf5-c25b73fbc89d)
After the update to v0.2.2:
![Image](https://github.com/user-attachments/assets/1118085a-2a5a-49e5-8ce2-5b2322c42d43)

**Comment by stringhandler** [comment]
![image](https://github.com/user-attachments/assets/31b6e1a0-6a7a-4eb4-87f7-80bf477d259a)

**Comment by mmrrnn** [comment]
Exactly, that's what I'm saying hahahha

**Comment by mmrrnn** [comment]
On linux the same. I can't test on mac for now.

Only one issue I've noticed is that the balance is updated after mining is started. Check out screen recording from my calculator:
https://github.com/user-attachments/assets/e3dae5b8-e70f-4546-8ede-cc6da2fd009b

**Comment by mmrrnn** [comment]
Auto update does not remove wallet dir with local database, that was my only trace

**Comment by stringhandler** [comment]
Closing for now. Will reopen this or a new issue if it happens again
