### ISSUE TITLE
0.2.8 Mac x86 has same hash rate on Eco and Ludicrous (used to be double on Ludicrous)

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#380]
**Describe the bug**
![image](https://github.com/user-attachments/assets/f8e1ece7-62cc-4e09-9065-e18e9380456d)

![image](https://github.com/user-attachments/assets/8535ce79-ffe0-49f9-9a49-2ff0d6ba0f7c)

**Comment by stringhandler** [comment]
@metalaureate please retest in 0.4.3
