### ISSUE TITLE
0.2.8 Mac x86 GPU does not mine

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#381]
**Describe the bug**
After 20+ minutes GPU still doesn't have a hash rate.

![image](https://github.com/user-attachments/assets/d21305ba-73a1-43cc-9c09-a90e2047a3ed)
![image](https://github.com/user-attachments/assets/972a5440-9234-4b73-a340-a4e1386a5936)
![image](https://github.com/user-attachments/assets/659d72e6-5689-4af7-beb5-73329c20e890)

**Comment by metalaureate** [comment]
[com.tari.universe.zip](https://github.com/user-attachments/files/16935589/com.tari.universe.zip)

**Comment by stringhandler** [comment]
@karczuRF another instance. I suspect this is due to not having opencl installed maybe?

**Comment by karczuRF** [comment]
Perhaps, I'm gonna investigate it

**Comment by karczuRF** [comment]
@metalaureate Could you please check which version of OpenCl and OpenCL do you have? You can find it like this:
- Click on the Apple icon in the top-left corner of your screen and select "About This Mac."
- Click "System Report," then go to the "Graphics/Displays" section. 
- The OpenGL and OpenCL version will be listed under the graphics card details.
