### ISSUE TITLE
v0.2.8 Monero address entry breaks down after initial submission

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#383]
**Describe the bug**
When I first log in to the new version, I can paste or type my Monero address into the Monero address field. If I delete the address or use the delet button to delete a character, the Monero address field becomes unusable. It will not take data. If I reset settings, the whole process will start from scratch. Thos might be a problem if the Monero address is subject to a reset. 

https://www.loom.com/share/959ed22a340c45978d09c6db3341e5fa?sid=c2d21480-dcf8-4bdf-a8e3-95afab0949d5

**To Reproduce**
1. After the application syncs and fully loads, Go to Settings > Monero address
2. Eneter a string in the Monero address field by typing or pasting an address (Do NOT click submit or cancel)
3. Close the Settings modal
4. Open setting modal and try to enter a monero address
5. Verify pasting does not work nor does typing. The field will not accept input. 
6. If you reset settings, the Monero field becomes editable again, i.e., will take input but the process repeats. 

**Expected behavior**
The Monero address field should be editable afte entering an address. You should be able to delete what is enetered and replace by pasting in a new address or typing in a new address. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS & Version: Mac M1 Sonoma 14.6.1
 - Browser & Version [e.g. chrome v71.0.12345]

**Comment by stringhandler** [comment]
@mmrrnn FYI
