### ISSUE TITLE
v0.2.8 Foreign Language settings not being applied consistently to all visible words/labels

### ISSUE THREAD

**Issue by ghost** [tari-project/universe#386]
**Describe the bug**
There is inconsistency in the words that are being translated depending on which language setting is configured. Some labels/words are not being translated at all. 

Video shows it best:
https://www.loom.com/share/fb4fbfe553e94751b4fe2740f1a53ba5

Mac M1 Sonoma 14.6.1

**Comment by Misieq01** [comment]
Resolved in pull request => #426
