### ISSUE TITLE
v0.2.9 Lost CPU Power display while mining. It never came back. 

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#411]
**Describe the bug**
Lost CPU Power display while mining. It never came back. 

Logs:
[Archive.zip](https://github.com/user-attachments/files/16947965/Archive.zip)

**Screenshots**
<img width="368" alt="Screenshot 2024-09-10 at 12 25 20 PM" src="https://github.com/user-attachments/assets/a122ca5c-d9e3-478c-ba9f-5020e6456441">

**Desktop (please complete the following information):**
 - OS & Version: Mac M1 Sonoma 14.6.1

**Comment by stringhandler** [comment]
Seems like a simultaneous event, perhaps a monero node was down?

**Comment by Cultmojo** [comment]
I have not witnessed this issue on v0.3.2
