### ISSUE TITLE
0.2.9 Windows: GPU Power doesn't display

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#414]
**Describe the bug**
The GPU Power never displays when mining. 

![Screenshot 2024-09-10 130005](https://github.com/user-attachments/assets/3e721f48-6c3d-4b48-b314-98f74c5b7557)

Logs:

[Windows_fresh_install (2).zip](https://github.com/user-attachments/files/16948972/Windows_fresh_install.2.zip)

**Desktop (please complete the following information):**
 - OS & Version: 
Windows 11 Pro
v23H2
OS Build 22631.3880
16GB RAM
x64
AMD Ryzen 5 5600GT with Radeon Graphics 3.60 GHz

**Comment by karczuRF** [comment]
Perhaps is solved with #442 .

**Comment by Cultmojo** [comment]
This is no longer a problem on v0.3.2

**Comment by Cultmojo** [comment]
This is no longer a problem on v0.3.2
