### ISSUE TITLE
0.2.9 Windows: I can't pause mining

### ISSUE THREAD

**Issue by Cultmojo** [tari-project/universe#416]
**Describe the bug**
When I click the Pause Mining button, mining continues, I lose CPU Power display (spins) the Pause Mining button spins and doesn't transfer back to Start Mining.

Logs:
[cant_pause.zip.zip](https://github.com/user-attachments/files/16949400/cant_pause.zip.zip)

**To Reproduce**
1. On a Windows machine, start mining
2. Click the Pause Mining button

**Screenshots**
![Screenshot 2024-09-10 133938](https://github.com/user-attachments/assets/c7fe5849-97ce-4726-8f40-13512d0b821b)

**Desktop (please complete the following information):**
 OS & Version:
Windows 11 Pro
v23H2
OS Build 22631.3880
16GB RAM
x64
AMD Ryzen 5 5600GT with Radeon Graphics 3.60 GHz

**Comment by Misieq01** [comment]
Also happened on macOS:
System: macOS 13.2.1
Platform: MacBook Air ( M1 Chip )
App Version: 0.2.10
Logs: [cannot-stop-mining-macos.zip](https://github.com/user-attachments/files/16961863/cannot-stop-mining-macos.zip)

Steps taken: 
- Open app
- Initialisation finished
- Mining starts automatically
- Button stuck on disabled state

![Image](https://github.com/user-attachments/assets/1e1d305b-e5e6-4ab8-9b3f-218ad62013b6)
