### ISSUE TITLE
0.2.9 Some shadow angles seems to exhibit funky graphical artefacts

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#418]
**Describe the bug**
Since we implemented solar tracking, we have sunlight angles that exhibit funky shadows.

![image](https://github.com/user-attachments/assets/7bf99bc1-5190-4c37-92fd-3f680c65945e)

Something similar can be seen with the Lusion demo:

https://tari-mining-visual.lusion.co/
x=7 y==0.6

**Comment by stringhandler** [comment]
![image](https://github.com/user-attachments/assets/48e14de5-e93f-4d74-bd9a-dd25ac2916ef)
