### ISSUE TITLE
v0.3 Reset settings clears the wallet balance

### ISSUE THREAD

**Issue by ghost** [tari-project/universe#445]
**Describe the bug**
When the user performs Reset Settings, their balance is reset to zero. 

Windows:
Seed phrase before reset: 
park protect north since taxi fruit rabbit donate current settle sail drip valley match lawn tree twist paper explain smooth medal glad wrist cable

Balance before reset:
13.949k tXTM 

Local time of reset (U.S. east coast): 
2.57

Seed phrase after reset: 
gate evil bounce slot seek borrow judge wear original rocket shallow task bitter rhythm muffin crunch member concert upgrade hint buyer reject tape stand

Logs:
[zero-balance-windows.zip](https://github.com/user-attachments/files/16968889/zero-balance-windows.zip)

Mac:
Seed phrase before reset: 
gate region morning same foam bacon noise kingdom code credit case file session calm replace always taste rally clarify two sibling evoke umbrella sunny

Balance before reset:
13k

Local time of reset (U.S. east coast): 
~3:00

Seed phrase after reset: 
scare simple truly share oppose source punch force history flight brain chapter federal mixture any clutch dune field room talk celery crack labor diamond

Logs:
[Archive.zip](https://github.com/user-attachments/files/16968945/Archive.zip)

**To Reproduce**
1.Have TU running with a wallet balance > 0. 
2. Click on "Reset Settings"
3. Verify wallet balance is now zero.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11 Pro
v23H2
OS Build 22631.3880
16GB RAM
x64
AMD Ryzen 5 5600GT with Radeon Graphics 3.60 GHz

Mac M1 Sonoma 14.6.1

**Comment by mmrrnn** [comment]
@stringhandler What exactly should reset include? I thought we reset(remove) everything Tari Universe created - whole config,cache,local dirs. Maybe we should rename it to "Return to initial state" or smth like this.

**Comment by stringhandler** [comment]
Can we have:
When you click reset settings, you get a popup: 

Clear:
[ ] Everything (Full reset)
[ ] Everything except wallet 


If you select everything except wallet, then it deletes everything except for wallet_config.json.

@metalaureate can we get some better wording here?
