### ISSUE TITLE
0.2.10 x86 Macs build their own chain on reset

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#446]
**Describe the bug**
After reset, chain height is 194
![image](https://github.com/user-attachments/assets/13d25d48-7565-4dcb-8739-76dd81a32dec)

**Comment by SWvheerden** [comment]
Should be fixed by tari release v1.4.2-rc.2, but that's going to require a db reset

**Comment by stringhandler** [comment]
Need to implement db reset
