### ISSUE TITLE
0.3.1 Mining has to be paused for settings to be changed but UI does not reflect this constraint

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#448]
**Describe the bug**
Mining, then turn CPU or GPU off. Doesn't work. Mining has to be Paused.

**Comment by Cultmojo** [comment]
I have not seen this on Windows or Mac. 
Mac M1 Sonoma 14.6.1
Windows 11 Pro
AMD Ryzen 5 5600GT

**Comment by stringhandler** [comment]
Can we rather change it so that you can turn mining on and off and the mining pauses while it changes?

**Comment by shanimal08** [comment]
PR: https://github.com/tari-project/universe/pull/553
