### ISSUE TITLE
I cannot know if I am connected to the Tari network

### ISSUE THREAD

**Issue by DWBCoreOfficial** [tari-project/universe#449]
**Describe the bug**

I often cannot connect to the Tari network unless I use a VPN, and even if I use a VPN, I cannot know if I have successfully connected to the Tari network

**Desktop (please complete the following information):**
 - windows11
 - 

**Additional context**

Suggestion: Add an option to see if you are connected to the tari network

**Comment by stringhandler** [comment]
suggestion for dev: Add a call to base node's GRPC to list connections. Then show this data in settings
