### ISSUE TITLE
x86 mac build their own chain

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#452]

**Comment by DWBCoreOfficial** [comment]
@stringhandler Windows is also prone to accidentally running its own chain

**Comment by SWvheerden** [comment]
Windows is most likely a network issue. 
Mac x86 was fixed with tari https://github.com/tari-project/tari/pull/6559
And released in v1.4.2-rc.2

**Comment by DWBCoreOfficial** [comment]
> Windows 最有可能是网络问题。Mac x86 已使用 tari [tari-project/tari#6559fix](https://github.com/tari-project/tari/pull/6559)，并发布于 v1.4.2-rc.2

Log prompt:
Due to incorrect response from the connecting party or unresponsive host after a period of time, the connection attempt failed

**Comment by DWBCoreOfficial** [comment]
> Windows is most likely a network issue. Mac x86 was fixed with tari [tari-project/tari#6559](https://github.com/tari-project/tari/pull/6559) And released in v1.4.2-rc.2

Log prompt:
Due to incorrect response from the connecting party or unresponsive host after a period of time, the connection attempt failed

**Comment by DWBCoreOfficial** [comment]
This doesn't seem to be my problem
