### ISSUE TITLE
0.3.2 fix number typography 

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#460]
**Describe the bug**
Kerning on the numbers is a little wide. -8% on Figma, should look like this.
![image](https://github.com/user-attachments/assets/af150121-085d-45a1-836c-a3103f3c73e9)

**Comment by shanimal08** [comment]
PR: https://github.com/tari-project/universe/pull/604

kerning was off because they're all actually in their own space (for the spinning animation) have made adjustments and still catering for the decimal character and unit, but please let me know if we need more adjustments
