### ISSUE TITLE
Xmrig not downloaded. Visual mode could not be displayed. Told to reset and getting “os error 303” after reset

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#463]
![ticket1969](https://github.com/user-attachments/assets/b200ea3b-9161-451e-9f9c-0efe7f1345ff)
![ticket1969-2](https://github.com/user-attachments/assets/238b3391-8f7b-4310-a5bf-940368c38d52)

**Comment by Misieq01** [comment]
Probably resolved in pull request => #259
