### ISSUE TITLE
When internet connection is lost, mining animation, block time continue to run. 

### ISSUE THREAD

**Issue by ghost** [tari-project/universe#476]
**Describe the bug**
v0.3.2
When an internet connection is lost, CPU and GPU mining is stopped/interrupted but the animation and block time counters continue to run as if the miner is still operational. 

A request to add some kind of user messaging when internet connection is lost:

"You're not connected to Tari Network"  or something to that effect.

**Comment by mmrrnn** [comment]
I'll do it along with #449
