### ISSUE TITLE
The response from the connecting host is incorrect or unresponsive

### ISSUE THREAD

**Issue by DWBCoreOfficial** [tari-project/universe#478]
Log prompt:
Due to incorrect response from the connecting party or unresponsive host after a period of time, the connection attempt failed

system: windows11
cpu: i7 11700 

Suggestion:

increase connection stability and support for TOR, you can use TOR to connect nodes

**Comment by stringhandler** [comment]
Let's add a setting "Use tor" and start it on windows if it is set

**Comment by DWBCoreOfficial** [comment]
@stringhandler  Also, it is recommended to increase support for TOR bridges and allow the use of bridges to connect to TOR

**Comment by brianp** [comment]
TOR Bridges have been added as an experimental feature in the settings. It is not on by default currently as MacOS suffers some tor related issues. but Windows, and Linux should work fine. Please feel free to test, and if it continues to be a problem we can re-open the issue.
