### ISSUE TITLE
Intermittent Tari node connection and disconnection handling

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#492]
**Describe the issue**
Bugs have been logged elsewhere about how the miner loses its connection to its node but continues in a zombie state.

When the connection to node is lost, an intermittent toast warning should say "Waiting for node to reconnect..." and if this doesn't happen for 30 seconds, then the miner to should change to the Stopped state.

An indicator in settings should show the current connection status.

**Comment by stringhandler** [comment]
Resolved
