### ISSUE TITLE
[0.3.3 Windows] Graphic display went blank

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/universe#506]
**Describe the bug**
Graphic display went blank, hide/show did not resolve and was only rectified after a restart.

**To Reproduce**
Universe was running for 2 days.

**Expected behavior**
The graphic display should not go blank.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Wndows 11 Pro

**Comment by brianp** [comment]
Old version. Lots of visual updates. Closing as probably resolved. We can re-open if still an issue.
