### ISSUE TITLE
Add a Beta  Pre-release opt-in flag to settings so that we can roll out to smaller group before everyone

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#518]
**Describe the issue**
Some updates escape internal testing. For these, we need to a pre-release flag in Settings for Tari miners to opt-in to allow us to auto-update them first before everyone else.

**Comment by mmrrnn** [comment]
I successfully created a MVP locally on Brian's WIP branch, incorporating the Tauri V2 upgrade. The integration with Runtime Configuration is promising, as detailed in the Tauri Updater documentation(https://v2.tauri.app/plugin/updater/#runtime-configuration).

info: We'll move updater logic to the rust command, where url will be dynamically defined regarding `pre_release` flag

**Comment by brianp** [comment]
Fixed with #1204
