### ISSUE TITLE
[0.3.7 Windows]/[0.3.3 Windows] Auto update clashes with User Account Control (UAC)

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/universe#524]
**Describe the bug**
Sometime during sleeping hours Universe auto-update activated and wanted to install v0.3.7 (from v0.3.3). UAC blocked it and needed user input. The issue was that this process was repeated umpteen times, resulting in umpteen UAC user prompts.

**To Reproduce**
1. Let Universe run and wait for the next release to be pushed with auto-update.

**Expected behavior**
Only one UAC user prompt is enough.

**Desktop (please complete the following information):**
 - Windows 10 Pro

**Comment by stringhandler** [comment]
This should already be resolved in next build. Please reopen if this is not the case
