### ISSUE TITLE
[0.3.3 MacBook Air M1 2020] CPU/GPU/tXTM calculations fail to restart following boot up from sleep mode on laptop

### ISSUE THREAD

**Issue by SolfataraEmit** [tari-project/universe#525]
**Description**
After the laptop has gone into sleep mode and a user resumes, if Tari Universe was running, it demonstrates the following behaviours on the interface:

* CPU/GPU/tXTM calculations no longer display, show the spinning "working" icon
* Layer remains fixed at current block, with five gaps in the blue block layer. It never appears to proceeds past this point.
* Current Block Time remains fixed.
* In the Options, the Debug message displays "Last timeLast block added to chain time 19985 days, 06 : 12 : 21"

This appears to be a result of xmrig terminating once the machine enters its sleep mode, given the xmrig logs terminating in the evening and resumption of the device was in the morning. Attached log, please let me know if you would require any other logs.

**To Reproduce**
1. Run Tari Universe and confirm calculations are being presented on interface and blocks are being worked on.
2. Lock your laptop and leave it overnight (or a reasonable period of inactivity to have the machine enter its sleep mode)
3. Log back in and note the described behaviours 

**Expected behavior**
Unsure. My assumption would be that it should either continue to work or, if the sleep mode does halt running services, that Universe would check for these and resume/restart them gracefully. 

**Desktop (please complete the following information):**
 - OS & Version: macOS 14.6.1

[xmrig.log](https://github.com/user-attachments/files/17054481/xmrig.log)

**Comment by stringhandler** [comment]
@SolfataraEmit can we retest this in 0.4.3 please?
