### ISSUE TITLE
[0.3.7 MacBook Air M1 2020] Universe continue to display estimated tXTM earnings despite both GPU and CPU mining being turned off.

### ISSUE THREAD

**Issue by SolfataraEmit** [tari-project/universe#526]
**Description**

Tari Universe continues to display an estimated tXTM earnings/day despite having turned off both GPU and CPU mining. Clicking on the "help" icon displays what I assume would be the correct earnings in each category: -.

**To Reproduce**
1. While Universe is running, turn off both GPU and CPU mining from the configuration options.
2. Wait for two minutes, noting that the estimated earnings continues to fluctuate.
3. Click on the help icon and note that the estimated earnings are blank.

**Expected behavior**
Would assume estimated earnings to be blank or zero if both GPU and CPU mining is turned off in Settings

**Screenshots**
![image](https://github.com/user-attachments/assets/9a39d908-e433-425f-9810-220fedce8cf1)
![image](https://github.com/user-attachments/assets/de9071e1-71a0-4656-a50a-e2d3302bda63)

**Desktop (please complete the following information):**
OS & Version: macOS 14.6.1

**Comment by mmrrnn** [comment]
I fixed it  here:
https://github.com/tari-project/universe/pull/493/files#diff-c7edac6a7d53d4fe9e7b2925cbe0201ccb544bc67729b753c4eeb08194155d67R62
