### ISSUE TITLE
Missing balance after update to TU 0.3.7

### ISSUE THREAD

**Issue by MarkusMeyer1** [tari-project/universe#533]
Description

-TU seeds added to Aurora after network reset
-Missing balance after update from Universe 0.3.6 to 0.3.7 is still displayed in Aurora

![IMG_8681](https://github.com/user-attachments/assets/156b8d9b-d40f-4637-8ef6-67e9357d8545)
<img width="358" alt="Ekran Resmi 2024-09-19 15 31 30" src="https://github.com/user-attachments/assets/1078dd92-e89e-4f99-b177-4b36e497c07d">

Tari universe 0.3.7
Aurora v0.27.0 (b757)

**Comment by stringhandler** [comment]
Solved by viewkey problem
