### ISSUE TITLE
0.3.7 Tari Universe does not recover out of laptop sleep mode

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#535]
**Describe the bug**
When I close my M1 laptop for some hours, and when I come out of sleep, the gpu and cpu spins and i can't stop.

<img width="1097" alt="Screenshot 2024-09-19 at 9 08 16 AM" src="https://github.com/user-attachments/assets/8354711c-f54d-4d7f-b4ed-0491615edf78">

**Comment by stringhandler** [comment]
Could not reproduce. Animation gets stuck.
