### ISSUE TITLE
[0.3.7, MacBook Air M1 2020] Pressing "Start Mining" while CPU/GPU mining have been toggled off in settings results in unresponsive state that requires restart

### ISSUE THREAD

**Issue by SolfataraEmit** [tari-project/universe#538]
**Describe the bug**
If a user disables CPU and GPU mining and then clicks the "Start Mining" button, Universe enters a state where the "Start Mining" button is greyed out and in a perpetual loading state. At this point, the user is unable to either stop this process or enable one of the mining methods from options via the front-end, and is forced to close and restart Universe.

Universe v0.3.7

**To Reproduce**
1. Make sure you are not currently mining.
2. Turn off GPU and CPU mining in options
3. Attempt to start mining. Note that the Start Mining button enters an unresponsive state and the user is unable to stop this or turn on any mining settings while this state continues.

**Expected behavior**
Either that the user is unable to start without at least one method of mining being turned on in settings, or a prompt to indicate that both methods are turned off and an option to turn them on before starting up.

Desktop (please complete the following information):
OS & Version: macOS 14.6.1

**Comment by mmrrnn** [comment]
I fixed it here:
https://github.com/tari-project/universe/pull/493/files#diff-f0ca09f63fec7da2a1848659282990334c8c2138474612d7562d0240924b0624R34

Mining Button is disabled when both cpu and gpu mining disabled in settings
