### ISSUE TITLE
Unable to shrink memory, killed process

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#542]
![image](https://github.com/user-attachments/assets/e8a4802b-6554-4912-b07f-5bf5322f4a70)

**Comment by mmrrnn** [comment]
### 1. We could improve performance/find memory leak if any
1. I see this is v0.3.7 - We've made many refactors/improvements from that time(split `status`, refactored both frontend and backend, added 1s max response time for fetching data etc.). This issue might not be valid anymore
2. We could increase the kill threshold or adjusting other system settings.
```sudo sysctl -w vm.min_free_kbytes=12288000```(enables the out-of-memory (OOM) killer to kill the task that triggered the OOM condition) or ```sudo sysctl -w vm.oom_kill_allocating_task=1``` (sets the minimum free memory threshold).
I'm not convinced to the second point tbh

**Comment by stringhandler** [comment]
Moving to under observation. Let's see if there are any more incidents of this

**Comment by brianp** [comment]
Closing as fixed. We can re-open any new issues if memory leaks are found.
