### ISSUE TITLE
0.3.9 Beta: When installing the miner, I find that the installation was stuck at 20%, a restart of the miner on the 3rd attempt resolved it

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#543]
**Describe the bug**
When I downloaded the mier, saavedd it to Applications and opened it, I found that the instaallation was stuck on 20% for over 20 minutes. 

**To Reproduce**
1. Download 0.3.9 beta version from: https://github.com/tari-project/universe/actions/runs/10948572087
2. Oncee downloaded, move to Applications
3. Open from Applications
4. Observe the installation process

**Expected behavior**
Miner install should happen within a couple of minutees

**Screenshots**
<img width="1492" alt="Screenshot 2024-09-20 at 10 59 07 AM" src="https://github.com/user-attachments/assets/c4faeb98-0354-4ced-baf3-32964ae1fdb7">

**Logs:**
[Archive.zip](https://github.com/user-attachments/files/17073250/Archive.zip)

**Desktop (please complete the following information):**
- MacBook pro 13 inch 2017, Two Thunderbolt 3 ports
- Processor: 2.3 GHz Dual-Core Intel Core i5
 - OS & Version:  Ventura 13.6.9
 - Browser & Version N/A

**Additional context**
Anziska's miner installed after she restarted the miner from initial installation. My miner has mioved from 20% after I killed the application for the 3rd time and then restarted

**Comment by Misieq01** [comment]
Probably resolved in pull request => #259

**Comment by stringhandler** [comment]
Pretty sure this is fixed. Please reopen if not
