### ISSUE TITLE
0.3.9 Beta: Toggles for CPU & GPU are disabled by default and non responsive

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#547]
**Describe the bug**
As a user after I've instaalled the Beta version 0.3.9 & started mining, I found that when I go to settings, the CPU & GPU mining toggles appear as disabled by default. I'm unable to toggle them to enabled

**To Reproduce**
1. Install 0.3.9 Beta
2. Start the application and click on `Start mining`
3. Click on thee Settings icon
4. Settings window should open
5. View the CPU & GPU Mining toggles
6. Toggles should appear as enabled
7. Try to enable the toggles by clicking on it
8. Go back too Mining dashboard
9. View GPU Power
10. Note GPU Power stays at 0 butt CPU power fluctuates

**Expected behavior**
User should be able to enable or disable GPU & CPU mining as they pleease

**Loom**
https://www.loom.com/share/3f21eada0eaa4e8a83a9f427b485ae2c?sid=f730d506-ba68-40b8-83e5-e276d6a04280

**Desktop (please complete the following information):**
 - OS & Version: Venture 13.6.9
 - Processor: 2.3 GHz Dual-Core Intel Core i5
 - Device: macBook Pro 13 inch, 2017, Two Thunderbolt 3 ports

**Logs:**
[Archive 2.zip](https://github.com/user-attachments/files/17074201/Archive.2.zip)

**Additional Notes:**
This is also happening to Anziska

**Comment by Anziskavds** [comment]
My device details is MacBook Air 13 inch M1, 2020.
<img width="467" alt="image" src="https://github.com/user-attachments/assets/0ed2893d-8d8e-4011-a911-82aec07ca8f1">

**Comment by Tas4tari** [comment]
I re-installed 0.3.7 and found the issue prevalent only on the CPU mining toggle:
https://www.loom.com/share/f30a9e8b5d954506b42936c5e5ec5282?sid=84d31613-eee3-488c-9fca-89f310febad6
Logs:
[Archive.zip](https://github.com/user-attachments/files/17077053/Archive.zip)

**Comment by stringhandler** [comment]
Closed in 0.4.0
