### ISSUE TITLE
0.3.9: Send Logs: CTA throws an error when trying to submit logs

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#550]
**Describe the bug**
As a user when I go to Settings in univer, select the `Send logs` CTA, and click on `Submit` I receive an erro

**To Reproduce**
1. Open Universe app
2. Start mining
3. Click on Settings icon
4. Settings window should open
5. Scroll to Logs
6. Click on `Send logs`
7. Click on the `Submit` CTA
8. Observe

**Expected behavior**
Logs should be successfully sent

**Video**
https://www.loom.com/share/7ffdb46b2ad34cf7943128b55e72c55a?sid=c9332546-5713-4444-aa3d-4ae42d223667

**Logs:**
[Archive 2.zip](https://github.com/user-attachments/files/17074494/Archive.2.zip)

**Desktop (please complete the following information):**
 - OS & Version: Ventura 13.6.9
 - Processor: 2.3 GHz Dual-Core Intel Core i5
 - Device: MacBook Pro: 13-inch, 2017, Two Thunderbolt 3 ports

**Comment by Anziskavds** [comment]
This is also happening for me.
My device details is MacBook Air 13 inch M1, 2020.
MacOS Sonoma Version 14.5
