### ISSUE TITLE
The block time doesn't reset after the miner was stopped

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#556]
**Describe the bug**
When a user stops(now pause but needs to be changed to stopped) the miner the block time should also stop and reset. Currently the block time continues a few seconds later than what is was when the user stopped the miner on when the user starts it again. When the user starts mining again the block time should start from the beginning(0:00) again.

**To Reproduce**
1. Start the miner
2. Look at the time stamp of the Block time
3. Click on Stop/Pause miner
4. Start the miner again
5. Look at the time stamp of the Block time.
6. Currently the Block time doesn't reset

**Expected behavior**
When the miner was stopped and the user starts the miner again the Block time should start from the beginning(0:00).

**Video**
(https://www.loom.com/share/1faabac985a54a02806a6debf58f39f7?sid=f1d184e0-5d55-4496-882a-9872d8a856a0)

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1, 2020
 - Browser & Version MacOS Sonoma 14.5

**Comment by stringhandler** [comment]
Please retest in 0.4.3

**Comment by mmrrnn** [comment]
@stringhandler  
I believe it's fixed here: https://github.com/tari-project/universe/pull/590
