### ISSUE TITLE
0.4.0-beta GPU mining is disabled on M1 & Windows

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#572]
**Describe the bug**
On load, GPU stays disabled.
![image](https://github.com/user-attachments/assets/a88550a4-39a2-4cbd-bdcf-77d4f62c1d22)

![image](https://github.com/user-attachments/assets/99b92c07-551a-4751-b8a9-a5865db5f031)

Was working before.

**Comment by stringhandler** [comment]
This is fixed in 0.4.5
