### ISSUE TITLE
Signup form is spamming email

### ISSUE THREAD

**Issue by gwatts** [tari-project/universe#59]
**Describe the bug**
Someone used my email address to signup for Tari (happens a lot) - I hit the "unsubscribe" button at the bottom of the email, but my address is continuing to be spammed with "One Last Step: Confirm your email for early access!" emails to be added to the waitlist for Tari Universe - 11 in the last 45 minutes.

Filing here in the hopes it reaches the right person instead of hitting the "spam" button on gmail and impacting your ability to deliver future emails.

![image](https://github.com/user-attachments/assets/0db7ddbe-7141-418e-a2de-05f7c1d1fc1c)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS & Version: [e.g. iOS 10.2.1]
 - Browser & Version [e.g. chrome v71.0.12345]

**Smartphone (please complete the following information):**
 - Browser & Version [e.g. stock browser v0.1.2]

**Additional context**

**Comment by metalaureate** [comment]
Thank you we are looking into this asap.

**Comment by gwatts** [comment]
@metalaureate not had any further after that last one at 7:40am (CDT); wondering if someone just get entering the same address repeatedly into a form, vs some other glitch.

**Comment by metalaureate** [comment]
Thanks, we pushed a fix to avoid this happening in the future.

**Comment by gwatts** [comment]
@metalaureate appreciate the quick response!
