### ISSUE TITLE
0.4.3 Sys icon earnings don't match app earnings

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#596]
**Describe the bug**
On MacbookAir, the estimated earnings in the toolbar icon is not matching what's shown in the window. Also, unminimize is is enabled, even when the window is not minimized.
![telegram-cloud-photo-size-1-5159225870165060562-y](https://github.com/user-attachments/assets/f8311366-5d2c-4c02-9278-653dcdd6f890)

**Comment by mmrrnn** [comment]
Unminimize issue also on linux
