### ISSUE TITLE
Gpu hardware stats device list

### ISSUE THREAD

**Issue by karczuRF** [tari-project/universe#611]
Refactor hardware parameters to return not only the single (first) one GPU device, but all detected ones, allowing for better gpu devices management (e.g. turning on/off specified) and controlling params like hashrate.

Example of use:
![Image](https://github.com/user-attachments/assets/d58e3b5a-f373-427f-9d91-e3e7b911037f)

**Comment by uforiaio** [comment]
After v0.4.x (?) the Intel on chip gpu is the only used one. Earlier versions didn't have the same behavior, but to be fair I wasn't watching close. Not sure if the gpu stats list has a guid/uuid that uses to order the cards. It's obviously not alphabetical. 

![image](https://github.com/user-attachments/assets/15fb572d-e326-4656-a9af-b380327d6d68)

**Comment by brianp** [comment]
Improvements made. Closing issue.
