### ISSUE TITLE
Block time has a few seconds delay before resetting

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#629]
**Describe the bug**
The block time doesn't reset immediately after a block was build. There is a few seconds delay on the block time.

**To Reproduce**
1. Go to the miner
2. Click on start mining
3. Wait for a block to build
4. Keep an eye on the block time
5. The block time should reset immediately after a block was done building
6. Currently there is a few seconds elay before the block time resets

**Expected behavior**
The block time should reset immediately after a block was done building

**Video**
(https://www.loom.com/share/8d86560d5d65420b96e200eea078939b)

**Desktop:**
 - OS & Version: MacBook Air 13 inch M1, 2020
 - Browser & Version: Sonoma 14.5

**Comment by stringhandler** [comment]
This logic has been updated again. Please retest @Anziskavds

**Comment by Anziskavds** [comment]
Tested successfully on Testnet 0.5.6. https://www.loom.com/share/0570291570654a84b5f579822418b5c9
