### ISSUE TITLE
Language doesn't change everywhere when it's being changed

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#631]
**Describe the bug**
When a user changes their language, only certain fields update to that language. All fields should update with the currently language that was selected by the user.

**To Reproduce**
1. Open general settings
2. Change the language from the dropdown
3. Confirm that all fields update to the language selected
4. Currently only certain fields change to the language selected

**Expected behavior**
All fields should changed to the laguage selected by the user

**Screenshots**
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/08bea2d5-0013-4cbe-ae60-e988efce6186">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1, 2020
 - Browser & Version Sonoma 14.5

**Comment by stringhandler** [comment]
@metalaureate has created a pr for this. I am going to close this as it's an ongoing fix
