### ISSUE TITLE
[0.4.6 Windows] Tower stopped showing dynamic blocks

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/universe#659]
**Describe the bug**
Tower stopped showing dynamic blocks

**To Reproduce**
1. Run Universe for a while

**Expected behavior**
Tower should show dynamic blocks

**Screenshots**

![image](https://github.com/user-attachments/assets/4f65198f-814e-4b3d-94cc-61b9d40d3ead)

**Desktop (please complete the following information):**
 - Windows 11 Pro

**Comment by stringhandler** [comment]
I believe this is solved in 0.5.13. Please confirm
