### ISSUE TITLE
0.5.4 Wallet shows undefined when it is really is zero

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#671]
**Describe the bug**

This state is great for "we're getting your wallet balance or we don't know it" but not good for when it really is zero. If we can't distinguish between the two states then we should revert to 0.

![image](https://github.com/user-attachments/assets/8df29254-27f6-4f2e-b42e-4f1cf5a2c3a4)

**Comment by shanimal08** [comment]
PR here already https://github.com/tari-project/universe/pull/667 

just please with the fix we hardly see the `-` since the initial value from BE is 0 😬 so it'll show up as 0 again
