### ISSUE TITLE
[i18n] Language for "Airdrop game" needs to be updated for non-english

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#680]
v0.5.6

Non-english language still says "Airdrop Game" when it should say "Claim gems"

**Comment by stringhandler** [comment]
Also the info icon is not translated 
![image](https://github.com/user-attachments/assets/ae0d217d-5436-4af7-8a8b-a8bc4b40edfe)

**Comment by brianp** [comment]
Closing as i18n is being managed.
