### ISSUE TITLE
0.5.6: Visual issue: When language is changed to Japanese, the text within the version pill appears cut off

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#698]
**Describe the bug**
OOn 0.5.6, when you change the language to Japanese, the text within the version pill appears cut off

**Steps to reproduce:**

1. Download the miner app, version 0.5.6
2. Complete installation
3. Click on Settings 
4. Click on General
5. Click on the Language drop down list
6. Scroll down and click on Japanese (found just below Bahasa Indonesia)
7. Close the Settings Modal
8. View the pill within the widget

**Video**
https://www.loom.com/share/72f8627fb9514816872d2e6befe706a8?sid=cd812cc9-df74-42cc-ae14-1231da0948eb 

**Desktop (please complete the following information):**
- MacBook Pro, 13 inch, 2017, Two Thunderbolt 3 ports
- Processor: 2.3 GHz Dual-Core Intel Core i5
- MacOS: Ventura 13.6.9

**Comment by brianp** [comment]
Assigned to @shanimal08 @peps @PanchoBubble 

This issue is here if someone wants to review component sizing. Please volunteer, or I'll close it as won't fix.

**Comment by brianp** [comment]
I'm sold. Let's close this for now, and if you find anything we can just open a PR, or create an issue if needed.
