### ISSUE TITLE
Reset setting gets stuck on loading

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#707]
**Describe the bug**
When a user reset the settings of Tari Universe, it takes a very long time for it to actually complete. The user has been stuck on loading for more than 15min now and the process haven't completed yet. It's still in loading state. Seems like the proces doesn't complete because it never took more than 5min to reset the settings.

**To Reproduce**
1. Go to settings
2. Click on General settings
3. Click on Reset settings
4. User gets stuck on loading

**Expected behavior**
Reset settings should complete in less than a minute

**Screenshots**
<img width="399" alt="image" src="https://github.com/user-attachments/assets/2937efbc-e36f-44f7-8284-9a6df57da38d">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 Sonoma 14.5
 - Browser & Version Testnet 0.5.7

**Comment by mmrrnn** [comment]
Currently esmeralda and nextnet directory contains only wallet_config. We would need to write custom method for deleting nested directories and checking whether they contain files/dirs we don't want to remove
