### ISSUE TITLE
GPU mining not activating on M2 Max

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#721]
**Describe the bug**

Installing fresh first time on M2 Max 0.5.7, gpu power never starts (multiple app restarts and reboots).

![image](https://github.com/user-attachments/assets/a8c60ce5-2ffa-4b9d-b443-9d6dae5bcfcd)

**Comment by stringhandler** [comment]
Need more info here please @metalaureate

**Comment by brianp** [comment]
May be fixed. Closing for now.
