### ISSUE TITLE
Many cases of crash on update OS error 10054

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#732]
**Describe the bug**
![telegram-cloud-photo-size-2-5188253651448228922-y](https://github.com/user-attachments/assets/fe48dfba-3e5e-4bf7-b39f-63fd0579b8ae)

![telegram-cloud-photo-size-2-5188253651448228930-y](https://github.com/user-attachments/assets/be519893-9c81-4086-9617-4073f62117f1)

Logs:
 f16db0e5-4b03-4793-8ca5-8c48849c9b68
615c4d43-fa71-4579-8dec-53ec13c314ff

**Comment by stringhandler** [comment]
Fixed when tor was moved to mirrors
