### ISSUE TITLE
Invalid digit error

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#736]
**Describe the bug**

![telegram-cloud-photo-size-1-4906770144932507254-y](https://github.com/user-attachments/assets/cd8c099d-8b83-408f-affb-1586640d1975)

log: a3bcfbce-4c60-47d5-bdf3-c1ad0204d040

but look at their app id--something not right there.

Re-install did not work. And reset didn't work:

"Rest Settings Failed Could Not Get App Directories"  Now I'm at a loading circle

![telegram-cloud-photo-size-1-4906770144932507257-x](https://github.com/user-attachments/assets/ed7c00e2-3543-4ceb-83a1-3f41194b9ee3)

**Comment by MCozhusheck** [comment]
Made additional logging to the sentry to find the cause of this error
