### ISSUE TITLE
Mac x86 stuck at 13% sync for 20 MINUTES

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#74]
**Describe the bug**
It used to work on my x86, but 0.1.34 just hangs at 13% sync--for 20 mins, and then completed. I wondered if there was a network time out or retying something or other going on for it to take so long.

Louis' x86 also hangs at 13%.

**Screenshots**
![image](https://github.com/user-attachments/assets/1e76d2fa-e4a7-4678-9cd9-a4940d0bf6c6)

**Desktop (please complete the following information):**
 - OS & Version: Big Sur 11.6.1

**Comment by stringhandler** [comment]
We should tie up the sync percentage to the amount of blocks that need to be downloaded. We should also add a step for downloading headers and add that to the progress
