### ISSUE TITLE
Beta version 0.5.10: Airdrop UI not visible

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#744]
**Describe the bug**
I find that when I am on the miner app version 0.5.10, the Airdrop UI is not visible even though `airdrop_ui_enabled` is set to true

**To Reproduce**
1. Download Beta version 0.5.10
2. Install and open the miner
3. Go to your profile > Library > Application Support > com.tari.universe.beta
4. Open the folder
5. Right click on app_config.json and open with text edit app
6. View `airdrop_ui_enabled` field and confirm that it is set to true
7. Go back to the miner app and view the widget on the left panel

**Expected behavior**
User should see the airdrop ui enabled within the miner

**Screenshots**
<img width="794" alt="beta config" src="https://github.com/user-attachments/assets/2620e0e1-b198-46ce-af98-d1bc688488ef">
<img width="1492" alt="No Airdrop integration" src="https://github.com/user-attachments/assets/46915d62-7fe1-404d-b47d-ee2d81cc0880">

**Desktop (please complete the following information):**
- MacBook Pro 15 inch, Intel Core i7
 - OS & Version: Ventura 13.7

**Logs**

[Archive.zip](https://github.com/user-attachments/files/17283595/Archive.zip)

**Comment by shanimal08** [comment]
should be fixed in 0.5.12 :D

**Comment by Tas4tari** [comment]
Tested in v0.5.12 and I am now able to view the Airdrop UI
