### ISSUE TITLE
Beta version 0.5.10: Pool Mining: Toggle is set to disabled even though within config this option is set to True and user is unable to toggle between enabled and disabled

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#746]
**Describe the bug**
As a user when I go to `Experimental Settings` and view `Pool Mining` I see that the toggle is set to disabled by default. However when I check the config, `p2pool_enabled` is set to true. If I try to toggle to enabled I am unable to 

**To Reproduce**
1. Download and install beta version 0.5.10
2. Open the app
3. Click on the Settings icon
4. Click on `Experimental`
5. View `Pool Mining`
6. Note: Pool Mining should be enabled, but currently shows as disabled
7. Click on the toggle to enable Pool Mining
8. Note: User is unable to toggle to enabled
9. Go to finder > User > Library > Application Support > com.tari.universe.beta > app_config.json
10. Right click on app_config.json and seelect to open with text editor
11. View `p2pool_enabled`
12. Confirm `p2pool_enabled` is set to true

**Expected behavior**
I should Pool Mining enabled by default. I should also be able to toggle between enabled and disabled within the `Experimental Settings` window within the Miner

**Screenshots**
<img width="1492" alt="Screenshot 2024-10-07 at 21 39 00" src="https://github.com/user-attachments/assets/65dff37e-21ab-432c-8334-1379192df7d7">
<img width="794" alt="Screenshot 2024-10-07 at 21 38 54" src="https://github.com/user-attachments/assets/983edaa9-2120-40d7-bbb0-19881f0c8b35">

**Desktop (please complete the following information):**
 - OS & Version: Ventura 13.7
- MacBook Pro 15 inch, Quad-Core Intel Core i7

**Logs**

[Archive.zip](https://github.com/user-attachments/files/17283756/Archive.zip)

**Comment by stringhandler** [comment]
fixed in 0.5.18
