### ISSUE TITLE
User doesn't receive the pop up for Auto update

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#753]
**Describe the bug**
When a user has the previous build installed and there is a new build, the user should receive a pop up informing them that there is a new build with the option to update to the new version. User doesn't receive this pop up on 0.5.10 to install the new build 0.5.11.

**To Reproduce**
1. Open Tari Universe(previous version)
2. User should receive a auto update pop up
3. Currently there is no pop up for the user to auto updat to the new build

**Expected behavior**
User should receive a Auto update pop up message on the previous sbuild to update to the new build.

**Screenshots**
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/fb3fd19a-cfa2-41cd-8708-10d6ed9eca90">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020, Sonoma 14.5
 - Browser & Version Testnet 0.5.10

**Comment by stringhandler** [comment]
Dupolicate
