### ISSUE TITLE
Mac x86 Eco vs Ludicrous makes no noticeable difference

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#76]
**Describe the bug**
Ludicrous hovers around 30% and 800 h/s. Eco is about the same.

**Desktop (please complete the following information):**
 - OS & Version: Big Sur 11.6.1
 
<img width="380" alt="Screen Shot 2024-08-20 at 2 17 13 PM" src="https://github.com/user-attachments/assets/6b5ad8d1-f38e-4380-919e-aabd43c1cee5">

**Comment by stringhandler** [comment]
I think the problem here is that the mining is not restarted when you change it.
