### ISSUE TITLE
Mac M1 stuck on wallet dependency, quitting and restarting clears that hurdle.

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#77]
**Describe the bug**

User is stuck on this 5% progress about wallet state (for 10 mins+)
![image](https://github.com/user-attachments/assets/4ec47e9f-5dab-4448-ac95-15cf32e21278)

OS: Sonoma

**Comment by stringhandler** [comment]
Could be related to the 403 issue when requesting releases from github

**Comment by Misieq01** [comment]
Tested on Mac M1, looks like it is resolved
