### ISSUE TITLE
0.5.18: Language translations: Text still appearing in English when user changes to a different language preference

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#785]
**Describe the bug**
- As a user I find when I am on the miner and change to a different language, when I view the `Airdrop` settings window, the following text is still in English
  - Connection
  - Logged in as
  - Disconnect
 - When I check the Estimated earning widget, the text is also visible in English despite the user having another language preference selected
 - When I change language to Polish, I find that the text & sub text for `Earn gems & make Tari Universe better` is still in English

**To Reproduce**
1. Install and open the miner
2. Ensure you are connected to Airdrop
3. Click on the `Settings` icon
4. Within `General` click on the language drop down
5. Select any language other than English
6. Go to the `Airdrop` settings window
7. View the `Airdrop` settings
8. Close Settings
9. On the miner widget, click on the `?` icon within the `Est tXTM/day` section
10. View the pop up text

**Expected behavior**
I should see the text displayed as the language preference I have set and not in English

**Screenshots**
<img width="1492" alt="Screenshot 2024-10-09 at 11 08 53" src="https://github.com/user-attachments/assets/b98fcbfd-d71d-4537-b192-162903a05fe7">

<img width="1492" alt="Screenshot 2024-10-09 at 11 35 18" src="https://github.com/user-attachments/assets/7fa73f1a-0f7e-4271-b4f8-dc6d568aac05">

**Desktop (please complete the following information):**
 - OS & Version: Ventura 13.7
 - MacBook Pro 15 inch Quad-Core Intel Core i7

**Smartphone (please complete the following information):**
 - Browser & Version [e.g. stock browser v0.1.2]

**Additional context**

**Comment by Tas4tari** [comment]
Also prevalent on Build 0.5.20, NextNet

**Comment by Tas4tari** [comment]
Prevaalent on 0.5.22:
With Deutsch, the TestNet rewards pop up text is still in English
`Experimental settings:`
For all language translations, the `GPU Mining devices` section is still in English
![Screenshot (98)](https://github.com/user-attachments/assets/54de1ea6-5770-4f60-bc70-00955977d457)
![Screenshot (97)](https://github.com/user-attachments/assets/ee8f432c-891d-4a59-a2f4-d588fef57e3c)
![Screenshot (96)](https://github.com/user-attachments/assets/4c237979-fc53-4edf-b9e2-1e01940819b3)

**Comment by Anziskavds** [comment]
This is also on MacBook Air 13 inch M1 2020 on Sonoma 14.5 on Testnet 0.5.22.

**Comment by Tas4tari** [comment]
Tested on Releasee version 0.5.24: Windows 11
Translations do not carry across the site, for Deutsch, the `earn gems and maake Tari Universe better` text and sub text is still in English as well. 
All the other translations mentioned in the above comments and description are still prevalent on v0.5.24:
![Screenshot (115) (1)](https://github.com/user-attachments/assets/06c39138-5528-4b84-b2ff-d774e2d2367a)

**Comment by Tas4tari** [comment]
Tested on Windows 11 on NextNet version 0.5.27. Issue still persists

**Comment by Tas4tari** [comment]
Tested on v 0.5.28 and this is still prevalent. Across all languaages, new settings text still appears in english for all languages:
![Screenshot (142)](https://github.com/user-attachments/assets/738b23a2-2c02-4b0c-9a94-0c6d4cab79ee)
![Screenshot (141)](https://github.com/user-attachments/assets/f8b17c6c-d839-44ef-8b1f-0b7062ca8511)
![Screenshot (140)](https://github.com/user-attachments/assets/5b4e0580-c186-460b-ac10-81269039e55f)
![Screenshot (139)](https://github.com/user-attachments/assets/056e5976-c6ce-4161-acde-a41e2ecea338)

**Comment by mmrrnn** [comment]
The problem is that all new texts are filled in English, to be replaced later by the target translation.

The only thing I can do is to add all the hardcoded texts to i18n so that they can be translated later from English

**Comment by mmrrnn** [comment]
I'll also add Lint rule for inline texts that aren't wrapped in i18n
