### ISSUE TITLE
Could not fetch a valid release JSON from the remote

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#787]
Seeing this happening in sentry. No extra stack unfortunately. I think this is raised from the javascript though

**Comment by mmrrnn** [comment]
We'll solve this problem by hosting Tari Universe releases in our CDN and point them in the `latest.json` file.

I don't have access to our CDN, so I'll contact with @leet4tari

**Comment by leet4tari** [comment]
I don't think that is the problem, this was when we added the beta build, without a copy of in the updater folder for beta. This is now in place - https://github.com/tari-project/universe/blob/main/.updater/beta-latest.json. 
  
But would be better to get the full url that is failing, just in case it's something else.  
  
Side note, Tari Universe already in the CDN, just not updated in the build yet.
