### ISSUE TITLE
If p2pool crashes, universe gets into a loop of "Already getting miner stats"

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#788]
To reproduce:
Start unverse with p2pool. 
Kill p2pool while mining.

Expected:
Universe shows an error.

Actual:
Logs just say:
![image](https://github.com/user-attachments/assets/3b5bbc48-bdc1-4d6b-bbd3-d403027b8ff9)

Note: I found this while testing a p2pool version that had a `todo` in it, but the above steps should also reproduce it

**Comment by MCozhusheck** [comment]
Can no longer recreate.
Tested on version 0.5.16
