### ISSUE TITLE
Start up on Windows takes a very long

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#791]
**Describe the bug**
When a user sets up Tari Universe on Windows machine, it took about 20min to set up. After the set up was done the user redirect to the miner but the "Start Mining" button stays on load and the miner is running.

**To Reproduce**
1. Set up Tari Universe on Windows
2. Set up takes a while to complete(20min)
3. User gets redirected to the miner
4. Start mining button is in a loading state and while the miner is running

**Expected behavior**
Start up/Set up should take this long and the Start mining button should be stuck on a loading state.

**Screenshots**
![Loading issue](https://github.com/user-attachments/assets/3b10f14a-69bb-495f-b9e0-44c79fb314cf)

**Desktop (please complete the following information):**
 - Windows & Version: Acer Aspire A315-59

**Comment by brianp** [comment]
Closing. Windows seems to run regularly now, and this issue is likely outdated. Please feel free to re-open if issue persists.
