### ISSUE TITLE
User is unable to Start/Stop/Restart miner on Windows

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#792]
**Describe the bug**
After a user set up their Tari Universe on the Windows machine the users "Start mining" button gets stuck on loading which makes it impossible for the user to start/stop/restart the miner.

**To Reproduce**
1. User should set up Tari Universe on Windows
2. User should get redirected to the miner
3. Start mining button is in the loading state
4. User is unable to click on the button to stop/restart the miner

**Expected behavior**
After Tari Universe was set up the user should be able to start, stop and restart the miner

**Screenshots**
![Loading state](https://github.com/user-attachments/assets/29cbbf71-d886-4074-b24b-e1c84733cb18)

**Desktop (please complete the following information):**
 - OS & Version: Acer Aspire A315-59

**Comment by brianp** [comment]
Closing. This must be fixed by now.
