### ISSUE TITLE
CPU and GPU Power is stuck on loading state

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#793]
**Describe the bug**
When the user opens up the miner they get stuck on a loading state. The miner has been open for about 30 min and it's still in a loading state. CPU and GPU Power is also in a loading state. Noting is running.

**To Reproduce**
1. Open the miner
2. Leave the miner open
3. User stays stuck on a loading state 

**Expected behavior**
As soon as the user open their miner the user should be able to start the miner, CPU and Gpu Power should be running when the miner is started.

**Screenshots**
![Loading state](https://github.com/user-attachments/assets/f807abe4-f528-4970-bdb4-abf4392a3d16)

**Desktop (please complete the following information):**
 - Windows & Version: Acer Aspire A315-59

**Comment by brianp** [comment]
This is an outdated issue and lots of changes have been made in this area. Feel free to re-open if issue persists.
