### ISSUE TITLE
Windows: 0.5.13: When I change between mining modes I receive an error

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#799]
**Describe the bug**
As a user when I am on tari universe and switch the mode from `Eco` to `Ludicrous` and back, I receive an error. Additionally when I restart tari universe, I am unable to do anything as `Start Mining` is greyed out, there is no Block time and CPU & GPU is on load

**To Reproduce**
1. Download and install tari universe on Windows 11
2. Start the miner
3. Go to `Mode` on the widget & click on the arrow
4. Select `Ludicrous` mode
5. User sees an error
6. Click on the `Mode` dropdown again and select `Eco`
7. User sees the error again

**Expected behavior**
I should be able to switch modes seamlessly and still be able to mine

**Screenshots**
![Screenshot (1)](https://github.com/user-attachments/assets/98f157e4-1722-4898-9266-6efed413bf7e)
![Screenshot (6)](https://github.com/user-attachments/assets/f55b734a-d7c8-4ee5-a070-2bfb9739614c)
![Screenshot (5)](https://github.com/user-attachments/assets/f0e69a92-5dfc-4291-b103-dcbc348fdc14)

**Desktop (please complete the following information):**
 - Acer Aspire A315-59
 - Microsoft Windows 11
 - System type: x64-based PC
 - Version: 10.0.22631 Build 22631
 - Processor: 12th Gen Intel Core i7-1255U, 1700Mhz, 10 Core, 12 logical Processor

**Logs**

[universe.zip](https://github.com/user-attachments/files/17310407/universe.zip)

**Comment by stringhandler** [comment]
More info 
![image](https://github.com/user-attachments/assets/c9a02b5f-ea41-4ae5-9828-ce743f63992f)

**Comment by mmrrnn** [comment]
@stringhandler It's obsolete. @Tas4tari confirmes she hasn't seen the error for a long while
