### ISSUE TITLE
Minotari_node that keeps running

### ISSUE THREAD

**Issue by MarkusMeyer1** [tari-project/universe#800]
Universe opens for control purposes. It is turned off without being allowed to connect... the next day the machine is restarted 2 times but the node is still running in the “network” tab in the activity monitor

<img width="862" alt="Ekran Resmi 2024-10-09 19 07 49" src="https://github.com/user-attachments/assets/f6a1905a-4f1a-415e-844e-c83ea5ffb68d">
<img width="564" alt="Ekran Resmi 2024-10-09 19 08 25" src="https://github.com/user-attachments/assets/0633c041-89fb-4e23-bffb-c8aa11e07f87">
<img width="557" alt="Ekran Resmi 2024-10-09 19 08 33" src="https://github.com/user-attachments/assets/7495fad3-7344-4211-96e4-4ba93b55471c">

**Comment by brianp** [comment]
Work has been done to help ensure the proper killing of processes this has *probably* been fixed. Feel free to re-open or create a new ticket if it's still an issue.
