### ISSUE TITLE
Auto Update doesn't work

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#810]
**Describe the bug**
User has Testnet 0.5.13 installed and there is a new build out(Testnet 0.5.17) The user didn't receive the auto update pop up to update to the new version/build.

**To Reproduce**
1. Open Tari Universe(0.5.13)
2. Wait for the miner to open
3. User is suppose to receive a auto update pop up
4. Currently the user doesn't receive any auto update pop up

**Expected behavior**
User should receive a auto update pop up when they open the previous build and there's a new build out

**Screenshots**
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/1646632d-2287-479e-9272-f1ef656d114c">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 
 - Browser & Version Sonoma 14.5

**Comment by brianp** [comment]
Auto update has been pretty consistent, and we can't seem to replicate it. If we continue to have issues in the future lets re-open.
