### ISSUE TITLE
0.5.17: Windows: Reset Settings: When I try to reset setting with the `Reset wallet` toggle disabled, I receive an error message

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#812]
**Describe the bug**
0.5.17: Windows: Reset Settings: When I try to reset setting with the `Reset wallet` toggle disabled, I receive an error message. I am however able to reset settings when I enable the reset wallet toggle to On

**To Reproduce**
1. Click on the Settings icon
2. User should see the General Settings window opened by default
3. Go to Reset Settings and click on the `Reset Settings` CTA
4. Ensure `Reset wallet` toggle is off
5. Click on Yes

**Expected behavior**
User should be able to Reset their settings with the Reset wallet toggle off

**Screenshots & video**
https://www.loom.com/share/3aacfbfd6ef04cc9a28e726a9e81ea38?sid=bae4e646-1470-4c0a-a62b-850d77c3581d
![Screenshot (38)](https://github.com/user-attachments/assets/0d05d4d5-a454-4cac-8b75-381673155df3)

**Desktop (please complete the following information):**

![Screenshot (39)](https://github.com/user-attachments/assets/069d7855-ebb3-4251-9a27-c6909e403f66)

**Logs:**
[log.zip](https://github.com/user-attachments/files/17331257/log.zip)

**Comment by Julietnacy** [comment]
@Tas4tari If you're getting an error when trying to reset settings with the Reset wallet toggle disabled, but it works when it's enabled, it might be a bug.Make sure your software is up to date.

**Comment by Tas4tari** [comment]
Hi @Julietnacy I've checked my software updates for Windows and it is up to date

**Comment by Tas4tari** [comment]
This is allso occuring on 0.5.18

**Comment by Julietnacy** [comment]
@Tas4tari and you’re still getting the error ?

**Comment by Tas4tari** [comment]
@Julietnacy Did not see this occur on 0.5.20. I was able to reset suuccesfully, will therefore close this issue
