### ISSUE TITLE
0.5.17: MacBook Pro: Unable to complete installation as it is stuck at 0%

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#814]
**Describe the bug**
On my Macbook, when I download the 0.5.17 version and run the application. It stays stuck on 0% for the installation and connnection status shows I am not connected. A restart does not resolve this

**To Reproduce**
1. Download the 0.5.17 version of the app
2. Open file
3. Move to Applications
4. Go to Applications and double click on tari universe to open
5. Observe

**Expected behavior**
My installation should complete seamlessly

**Screenshots**
<img width="1492" alt="Screenshot 2024-10-10 at 16 02 56" src="https://github.com/user-attachments/assets/33908ba1-075e-4b39-8c16-ad0e708e6cf3">

**Desktop (please complete the following information):**
- MacBook Pro 15 inch - 2.9 Ghz Quad-Core Intel Core i7
- MacOS: Ventura 13.7

**Comment by brianp** [comment]
Stale issue. Probably fixed.
