### ISSUE TITLE
Invent a way to stop people mining on orphan chains

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#815]
**Describe the bug**
There must be a way to stop people from mining on an orphan chain or telling them that they have unverified funds. It is a huge source of confusion, disappointment, and time-consuming to support.

**Comment by stringhandler** [comment]
Maybe connect to the nextnet text or normal explorer and get the block height and then show a warning below the mining button "You seem to be connected to a fork, and not the main chain. Any blocks you win might be invalidated."

**Comment by stringhandler** [comment]
Use moneropulse
