### ISSUE TITLE
Universe App: Experimental Settings: When Tor is toggled off, user is not asked to restart

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#816]
**Describe the bug**
As a user I find when I toggle Tor off I am not asked to restart. Confirmed on app version 0.5.18

**To Reproduce**
1. Open tari universe
2. Click on the Settings icon
3. navigaate to Expeerimeental Settings
4. Scroll down to Tor
5. Tor should be enabled by default
6. Disable Tor by turning the toggle off
7. Observe

**Expected behavior**
User should be asked to restart the app, currently the user is not asked to restartthe app

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, version 23h2

**Comment by stringhandler** [comment]
monero address, import seed words.

**Comment by shanimal08** [comment]
@stringhandler added to monero address change too, but import seed words restarts automatically from the rust side, so don't want to mess with that. fine to just add some messaging saying there saying it will restart?
