### ISSUE TITLE
0.5.18: Windows: When toggling Pool Mining on/off and the app is restarted, I see flashing black screens 

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#821]
**Describe the bug**
As a user I find that when I toggle Pool Mining off or back on and the app restarts, there is a black screen that flashes for less than aa second. This happens until the app is opened and the miner starts

**To Reproduce**
1. Go to Settings
2. Select Experimental settings
3. Go to Pool Mining
4. Turn the toggle off
5. Click on `Restart` CTA on the pop up that appears
6. Observe as the app restarts

**Expected behavior**
The app should restart with no issue, and there should be no window/screen that flashes during this process

**Video**
https://www.loom.com/share/bdf4f479a87b4d27acd3d4477542b651?sid=16f53af8-50ca-4093-a0e5-b9361647803a

**logs:**
[logs.zip](https://github.com/user-attachments/files/17341104/logs.zip)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, version 23H2

**Comment by Tas4tari** [comment]
This is still occurring on NextNet version 0.5.20

**Comment by Tas4tari** [comment]
On nextNet version 0.5.22, I find that this is moe persisteent now. wheneever I'm requested to resstart the app and confirm, I see the flashing black screens

**Comment by Tas4tari** [comment]
This is still an issue on Release version 0.5.24

**Comment by Tas4tari** [comment]
Tested on Nextnet version 0.5.25 on Windows 11 and this is still an issue. Especially when I closee of the aapp and restart it

**Comment by Tas4tari** [comment]
Tested on Nextnet version 0.5.27 on Windows 11 and this is still an issue.

**Comment by Tas4tari** [comment]
Tested on v0.5.28, isssue is still occurring

**Comment by mmrrnn** [comment]
There must be "creation_flags(PROCESS_CREATION_NO_WINDOW)" missing somewhere

**Comment by Tas4tari** [comment]
Testeed on Windows 11, app version 0.5.56 and this issue is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.5.58 and this is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.5.60 and issue is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.61 and this is still an issu

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.63 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.2 and this is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.4 and this is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.6 and this is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.14 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.16 and this did not occur

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.17 and this did not occur. I will leave it open for one more release to confirm before closing

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.7.0 and this is no longer occurring
