### ISSUE TITLE
0.5.18: Import seed words: On Windows when i paste in my seed words, I am stuck on the `Importing wallet` screen

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#827]
**Describe the bug**
Failed on Windows 11, 12th Gen Intel(R) Core(TM) i7-1255U 1.70 GHz
I tried twice and was stuck on the Importing wallet loading screen for more than 10 minutes. The app does not restart on it's own. 
In order to get out of this state, I have to close the app and then restart it

**Additional Context:**
When restarted, if I go back and check the `Seed words` it looks like they had successfuly imported, the wallet emoji address also updated successfully. (I could not confirm wallet balance and tx history as my wallet is at 0 currently)

**To Reproduce**
1. Go to Setings
2. Go to Wallet
3. Click on the edit icon
4. Remove current seed words
5. Paste in a different set of seed words
6. Click on the check mark
7. App is greyed out and `Importing wallet` loading state is shown to the user (stays like this for 10+) minutes

**Expected behavior**
When I aadd in new seed words, I expect the import wallet process to be quick and the app to restart on it's own

**Screenshots**
Windows stuck on loading state:
![Screenshot (77)](https://github.com/user-attachments/assets/59494f64-b45b-433e-827a-ddb7114569bf)
After manually closing and then re-opening the app the details did import successfully:
![Screenshot (78)](https://github.com/user-attachments/assets/5f57a334-fe3e-4b5a-a9db-390c90986441)

**Desktop (please complete the following information):**
- Windows 11, 12th Gen Intel(R) Core(TM) i7-1255U 1.70 GHz, version 23H2

**Logs**
[logs (1).zip](https://github.com/user-attachments/files/17342292/logs.1.zip)

**Relates to:**
https://github.com/tari-project/universe/pull/767

**Comment by Tas4tari** [comment]
This is also occurring on NextNet version: 0.5.20

**Comment by stringhandler** [comment]
Also failing on 0.5.22

**Comment by Tas4tari** [comment]
Tested on Windows 11, version 0.5.28 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on 0.5.56 on Windows 11 and this no longer seems to be an issue as wallet imported successfully and app was restarted therefore will close this
