### ISSUE TITLE
Move P2pool to it's own settings tab

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#828]
**Describe the bug**
Observed half-dozen examples of this confusion;

<img width="314" alt="Screenshot 2024-10-11 at 7 08 22 AM" src="https://github.com/user-attachments/assets/c1fd53d4-b026-43cf-89f6-7e235c1d12d3">

**Comment by shanimal08** [comment]
@stringhandler @metalaureate to its own tab or to mining tab ? (since we aren't showing stats right now)

**Comment by mmrrnn** [comment]
Maybe we should move it to the "Mining Tab" it's just one toggle

**Comment by mmrrnn** [comment]
![Image](https://github.com/user-attachments/assets/8773f624-e4e8-4a0c-b80b-9d35bffd37f5)
