### ISSUE TITLE
UI/UX Queuing of Operational Commands While Waiting for Synchronous Processes

### ISSUE THREAD

**Issue by uforiaio** [tari-project/universe#832]
_Note: My AI Cluster is very limited while I mine Tari, so I don't have aider/cursor running better models. I am using llama3.1 70B/Q8, so it's not perfect, but when providing suggestions on things I like to provide at least an attempt for code analysis/suggestions to help make sense for myself to explain, as well as for others to review the bug/suggestion. When I slow down the mining in the coming weeks, I will be able to provide pre-validated non-compiled code as a suggestion that could be reviewed._

**Description:**

In the current client version (v0.5.18) and all other version, users experience a lack of responsiveness in the UI while synchronous backend operations are in progress. For example, switching modes (e.g., from "ECO" to "Ludicrous") or applying other settings requires users to wait until all backend operations are complete. This leads to user frustration and the perception of an unresponsive UI.

**Proposed Enhancement:**

By implementing a command queuing system that keeps the UI interactive, queues user commands, and processes them after backend operations are finished. This will include:

- Command Queuing: Display a list of pending operations initiated by the user.
- Real-Time Feedback: Notify users of the progress or status of each queued operation.
- Optimistic UI Updates: Immediately reflect changes in the UI before the backend confirms the operation. Rollback changes if errors occur.
- Error Handling: Notify users of failures (e.g., network issues, antivirus interference) and provide troubleshooting steps.

**Front-End Changes:**

1. Command Queuing UI:

- Create a visual list that shows all pending operations initiated by the user.
- Utilize state management to track these commands in the UI.

```
const [queuedCommands, setQueuedCommands] = useState([]);

// Function to add a command to the queue
function addCommandToQueue(command) {
  setQueuedCommands(prev => [...prev, { command, status: 'Pending' }]);
}

// Rendering pending operations
return (
  <div>
    <h3>Pending Operations</h3>
    <ul>
      {queuedCommands.map((cmd, index) => (
        <li key={index}>
          {cmd.command} - {cmd.status}
          {cmd.status === 'Pending' && <Spinner />}
        </li>
      ))}
    </ul>
  </div>
);
```

2. Optimistic UI Updates:

Update the UI immediately when a user action is initiated, and revert it if the backend fails to confirm the change.

```
const handleModeSwitch = (newMode) => {
  setMode(newMode); // Optimistic update

  sendModeSwitchToBackend(newMode)
    .then(response => {
      // Confirm success
    })
    .catch(error => {
      setMode('ECO'); // Rollback in case of failure
      alert('Failed to switch mode. Try again.');
    });
};
```

**Back-End Changes:**

1. Task Queue:

- Asynchronous management of user commands, ensuring they are processed in order, even while synchronous tasks are running.

2. Real-Time Feedback:

- Use WebSockets or Server-Sent Events (SSE) to communicate status updates back to the front-end.

3. Error Handling:

- Provide detailed error messages to the front-end for debugging and allow the system to handle network or environment-related failures.

**Back-End Code Example (Rust)**

```
use tokio::sync::Mutex;
use std::sync::Arc;
use std::collections::VecDeque;

#[derive(Debug)]
struct Command {
    command_type: String,
    payload: String,
}

struct CommandQueue {
    queue: VecDeque<Command>,
}

impl CommandQueue {
    fn enqueue(&mut self, command: Command) {
        self.queue.push_back(command);
    }

    fn process_next(&mut self) -> Option<Command> {
        self.queue.pop_front()
    }
}

#[tokio::main]
async fn main() {
    let command_queue = Arc::new(Mutex::new(CommandQueue { queue: VecDeque::new() }));

    // Enqueue a command
    let queue_clone = Arc::clone(&command_queue);
    tokio::spawn(async move {
        let mut queue = queue_clone.lock().await;
        queue.enqueue(Command { command_type: "SwitchMode".to_string(), payload: "Ludicrous".to_string() });
    });

    // Process commands
    tokio::spawn(async move {
        let mut queue = command_queue.lock().await;
        while let Some(command) = queue.process_next() {
            println!("Processing command: {:?}", command);
            // Handle the command
        }
    }).await.unwrap();
}

```

**Error Handling and Notifications:**

- In the event of an error (e.g., antivirus interference or network issues), provide clear notifications to the user.
- Ensure the user can troubleshoot common issues and retry the operation if necessary.

**Licensing and Open-Source Considerations:**

The following open-source technologies are used:

- React and TypeScript are licensed under the MIT License.
- The back-end uses Rust and its associated libraries like tokio and warp, which are licensed under Apache 2.0.

**Comment by brianp** [comment]
What tasks exactly are you trying to perform all at once? 

>  For example, switching modes (e.g., from "ECO" to "Ludicrous") or applying other settings requires users to wait until all backend operations are complete.

This isn't true.

You can do things like open the settings and perform additional actions while Eco is switching to Ludicrous. The UX isn't in fact locked up, it's actually just waiting to update. If you perform other actions like changing settings it will also function. There are certain things you can't do if they're related. Like you cant adjust miner settings specifically while the miner is in a state of change. But that's not so bad.

The likelihood we're going to remodel the app for command queuing right now is low although we appreciate your efforts in outlining what would be required, and we'll most definitely consider it in the future.

**Comment by uforiaio** [comment]
Just as a fyi, I suggested this a month ago when the front-end was having async hangs. It has become much more clean, so adding tasks to a queue watcher would clean it up, based on the issues, it's a very low priority. When TU launched, something was needed. 

Cheers :)
