### ISSUE TITLE
User doesn't get asked to restart when they disable Tor on Tari Universe

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#837]
**Describe the bug**
When a user disables Tor on Tari Universe they don't get asked to restart. It looks like nothings happening when the user disables and enables Tor.

**To Reproduce**
1. Go to Settings
2. Click on Experimental 
3. Disable Tor
4. User should get asked to restart
5. Currently nothing happens when the user disables Tor

**Expected behavior**
User should get asked to restart.

**Video**
https://www.loom.com/share/ed3ecbba8b094090adb4f170a728e417

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnest 0.5.20

**Comment by Tas4tari** [comment]
This is reesolved on 0.5.22 on Winddows 11
