### ISSUE TITLE
User gets a critical error when they try to reset their settings on Tari Universe

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#838]
**Describe the bug**
When a user tries to reset their setting on Tari Univers the user receives a critical error pop up message saying "Failed to setup application: Error extracting version: Version { major: 0, minor: 1, patch: 16 }. Error: unable to locate the end of central directory record
Please try again later. If the problem persists, please contact us."
When the user closes Tari Universe and the open it again the error stays there. I even tried to delete Tari Universe and installed it again but the error stays on my miner. I am unable to do anything on my miner.

**To Reproduce**
1. Go to settings
2. Click on General settings
3. Click on rest settings
4. User receives a loading screen and shortly after they get a critical error pop up message

**Expected behavior**
User should be able to reset their seeting without any errors.

**Screenshots**
<img width="939" alt="image" src="https://github.com/user-attachments/assets/db7817fc-e174-4aaf-9a3b-2cd036c4be57">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020, Sonoma 14.5
 - Browser & Version Testnet 0.5.20

**Comment by brianp** [comment]
Can't reproduce
