### ISSUE TITLE
0.5.20: NextNet:  GPU not being detected

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#843]
**Describe the bug**
As a user I find that when I intstall the tari universe aapp and begin to mine, my GPU is not being detected as it currently shows as `-` 
When I check Experimentaal settings I see that it states `No GPU Found`

**To Reproduce**
1. Download and install build 0.5.20
2. Open the app
3. Verify app starts Mining
4. View GPU Power
5. GPU Power should be visible and counting (For me it stays at `-`)
6. Click on Settings icon
7. Go to Experimental settings
8. Enable Experimental Settings with the toggle
9. View GPU Mining device section

**Expected behavior**
User should see GPU Mining device section list the device you are using and user should be aable to mine using GPU

**Screenshots**
![Screenshot (87)](https://github.com/user-attachments/assets/e6020c02-cd41-4fe9-95d6-9711a44d0a81)

![Screenshot (88)](https://github.com/user-attachments/assets/0ce1d80e-009d-4ca2-bb67-6184e9355040)

**Desktop (please complete the following information):**
 - Acer 315-59
 - Windows 11, version 23H2
 -  12th Gen Intel(R) Core(TM) i7-1255-U 1.70GHz

**Logs**
[logs (2).zip](https://github.com/user-attachments/files/17366329/logs.2.zip)

**Comment by Tas4tari** [comment]
Tested on release version 0.5.22, also an issue there as well:
Windows 11,  12th Gen Intel(R) Core(TM) i7-1255-U 1.70GHz

**Comment by Tas4tari** [comment]
Tested on release version 0.5.24, also an issue there as well:
Windows 11, 12th Gen Intel(R) Core(TM) i7-1255-U 1.70GHz

**Comment by Tas4tari** [comment]
Tested on Windows 11 on NextNet version 0.5.25 and GPU is not detected and not running

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version: NextNet 0.5.27 and issue is still prevalent

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version: NextNet 0.5.28 and issue is still prevalent

**Comment by Tas4tari** [comment]
This is still prevalent on Windows 11, on app version 0.5.56. I looked through the logs and noticed a few errors and warnings related to this:
[universe.zip](https://github.com/user-attachments/files/17568818/universe.zip)
![Screenshot (173)](https://github.com/user-attachments/assets/8b0085c4-a6ed-4618-97c7-34a289f20d5a)
![Screenshot (174)](https://github.com/user-attachments/assets/b2624636-9ad8-493f-a28b-c25f36dd60a8)

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.58 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.5.60 and this is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.5.61 and this is still occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.2. GPU is now being detected within `Mining` settings section, however GPU Power on the mining widget still displays as null:
![Screenshot (219)](https://github.com/user-attachments/assets/abf5ec0d-c7e5-439b-93bd-ec4b20d06afe)
![Screenshot (220)](https://github.com/user-attachments/assets/4f6a38c5-7c09-49a2-89c7-4db7c260d7a6)
![Screenshot (221)](https://github.com/user-attachments/assets/192064d4-a7ea-4e74-9333-9fc815438319)
![Screenshot (222)](https://github.com/user-attachments/assets/edbb75d2-5669-4e52-8204-f3fec0d95bd5)

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.4. GPU is now being detected within Mining settings section, however GPU Power on the mining widget still displays as null and logs still give of errors:
![Screenshot (227)](https://github.com/user-attachments/assets/843327bb-6e4c-4a59-853b-c983a3d26610)
![Screenshot (226)](https://github.com/user-attachments/assets/a93535a2-d056-4c0c-ab2a-2d327eb9ac27)

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.6. GPU is now being detected within Mining settings section, however GPU Power on the mining widget still displays as null and logs still give of errors:
Referenced issue:

https://github.com/tari-project/universe/issues/1044

**Comment by brianp** [comment]
Closing in favour of #1044
