### ISSUE TITLE
Windows: Experimental settings, and pool mining settings in particular, aren't being persisted 

### ISSUE THREAD

**Issue by expez** [tari-project/universe#845]
**Describe the bug**

Experimental settings aren't persisted => unable to pool mine.

Whenever I restart the app (which is required to enable pool mining) the experimental settings are toggled to off.  If I leave the pool mining stuff alone, and turn off e.g. visual mode, the settings are applied until tari universe is restarted.

**To Reproduce**
1. Go to Settings
2. Click on experimental
3. Change something
4. Restart tari universe
5. Experimental settings is now disabled and all experimental settings reset to their default value.

**Expected behavior**
I can change experimental settings, like all the other settings which work perfectly.

**Desktop (please complete the following information):**
 - Windows 11

**Comment by brianp** [comment]
similar to #987. Closing this as #987 encapsulates a bit more, but also covers this.
