### ISSUE TITLE
0.5.22 CPU mining not working after update

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#848]
**Describe the bug**

CPU not loading after update, was working fine in previous versions.

Logs: e59c5f2d-4017-4da3-b101-038e93286e88
![telegram-cloud-photo-size-5-6082249500677751136-m](https://github.com/user-attachments/assets/35ffb65a-73d2-4c32-b1e9-814cbeb4e2c2)

**Comment by brianp** [comment]
Stale issue has been fixed.
