### ISSUE TITLE
Release version: 0.5.22: When user toggles Tor off, when they are asked to restart and select Cancel, the Tor toggle is still visible as disabled

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#849]
**Describe the bug**
As a user I find, when I click on the Tor toggle to disable Tor, there is a pop up requesting the user to `Restart Tari Universe`, when I click on the `Cancel` CTA within the pop up. I find that Tor was still disabled despite me refusing to restart the app. When I checked my app config, I found that Tor was still set to False

**To Reproduce**
1. Go to 'Experimental Settings'
2. Enable the toggle to view Experimental Settings
3. Scroll to `Use Tor`
4. User should see the toggle enabled
5. Click on the toggle to disable it
6. User should see a `Restart Tari Universe?` pop up
7. Click on the `Cancel` CTA within the pop up
8. Pop up should close
9. View the `Use Tor` toggle

**Expected behavior**
User should see the `Use Tor` toggle still enabled & when they check app config, they should see Tor is still enabled

**Screenshots**
![Screenshot (101)](https://github.com/user-attachments/assets/8fe7b47a-e12f-4e7e-ab6c-76f6b59f4224)
![Screenshot (102)](https://github.com/user-attachments/assets/1717f71b-bb29-4ff2-8a04-335ba0881c9e)
![Screenshot (100)](https://github.com/user-attachments/assets/da0d511d-6d3b-4261-8d42-f72a6493a2bb)

**Desktop (please complete the following information):**
 - Acer 315-59
 - Windows 11, version 23H2

**Comment by Anziskavds** [comment]
This is the same on MacBook Air 13 inch M1 2020 on Sonoma 14.5 on Testnet 0.5.22.

**Comment by Tas4tari** [comment]
Tested on Release version 0.5.24 and issue is still prevalent

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version: NextNet 0.5.27 and issue is still prevalent

**Comment by Tas4tari** [comment]
Tested on Windows 11, on app version 0.5.56. and this is still occurring when I close the pop up by clicking on the `X` icon

**Comment by Tas4tari** [comment]
Tested in Windows 11, app version 0.5.60 and this still occurs

**Comment by brianp** [comment]
UX Issue may be fixed in the future. Closing for now as it's low priority.
