### ISSUE TITLE
Release version: 0.5.22: WebGL errors still prevalent on Sentry

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#851]
**Describe the bug**
When checking Sentry, I founnd that there are still WebGL issues that are showing up:
https://tari-labs.sentry.io/issues/?end=2024-10-15T11%3A31%3A59&environment=production&groupStatsPeriod=auto&project=4507979991285760&query=release%3Atari-universe%400.5.22&sort=freq&start=2024-10-14T17%3A06%3A00
**Screenshot:**
<img width="1552" alt="Screenshot 2024-10-15 at 1 40 25 PM" src="https://github.com/user-attachments/assets/bcae6ec1-c595-4fec-b3a7-194033cbbd87">

**Comment by mmrrnn** [comment]
![Image](https://github.com/user-attachments/assets/53ec061a-c878-4823-8cd2-aae8531ccfc2)


```
 2024-11-07 12:38:00.624873601 ERROR "THREE.WebGLRenderer: Error creating WebGL context."
 2024-11-07 12:38:01.226404014 INFO  "Updater event" "Log Item" "UPTODATE"
 2024-11-07 12:38:01.422842358 INFO  "Updater event" "Log Item" "UPTODATE"
 2024-11-07 12:39:10.836055560 INFO  "Mining starting...."
 2024-11-07 12:39:10.836213986 INFO  "Fetching applications versions"
 2024-11-07 12:39:10.836265539 INFO  "Fetching applications versions"
 2024-11-07 12:39:10.850584119 INFO  "Mining started."
```

all the time on my appImage build on ubuntu. It works fine on dev and manual build

**Comment by mmrrnn** [comment]
LINUX
--
During testing, I have noticed that there is a difference in behavior between my local build and the public build in terms of losing the WebGL context. This issue seems to be related to the fact that the local build was created on different hardware than the public build, causing compatibility issues with the WebGL context.

**Comment by brianp** [comment]
Does this context error actually prevent the visuals from rendering?

If so, is there any way we can check for disabled hardware acceleration then
- not initialize the visuals
- disable visual mode by default, and not allow it to be enabled
