### ISSUE TITLE
Release version: 0.5.22: Airdrop related errors showing up on Sentry

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#853]
**Describe the bug**
When I check Sentry for v0.5.22 I find that there are airdrop related issues

**Link:**
https://tari-labs.sentry.io/issues/5980121880/?end=2024-10-15T11%3A31%3A59&environment=production&project=4507979991285760&query=release%3Atari-universe%400.5.22&referrer=issue-stream&sort=freq&start=2024-10-14T17%3A06%3A00&stream_index=1

**To Reproduce**
<img width="1552" alt="Screenshot 2024-10-15 at 3 17 02 PM" src="https://github.com/user-attachments/assets/954393ed-ccf1-44c4-9a01-d89cdc4ae9a7">

**Comment by brianp** [comment]
Issue isn't occuring on 0.6.0+ Closing as fixed. If we see it after the 0.7.3 release on an 0.7 version then we will re-open.
