### ISSUE TITLE
When a user sends some tXTM it doesn't deduct from the wallet balance

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#862]
**Describe the bug**
When a user sends(from Aurora) some tXTM the amount shows up in the users history but the amount doesn't deduct from the wallet balance.

**To Reproduce**
1. Have the miner open and running
2. Keep an eye on your wallet balance
3. Import the wallet on Aurora
4. Send a transaction
5. Look at the wallet balance 
6. Look at the wallet history
7. Currently the tXTM doesn't deduct from the wallet balance but it does show up in the users history as a added transaction

**Expected behavior**
When a user sends some tXTM the amount they send should deduct from the wallet balance

**Screenshots**
<img width="369" alt="image" src="https://github.com/user-attachments/assets/ea99809b-e10f-4daf-9594-28b81b3a248e">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnet 0.5.22

**Comment by Anziskavds** [comment]
I haven't experienced it as of yet on the new build Testnet 0.5.27. This is an existing issue I'm just mentioning here. I logged it on Testnet 0.5.22.

**Comment by stringhandler** [comment]
This does add up though, it's just getting cut off. We only show one decimal place. @metalaureate maybe we need to expand the decimal places?

**Comment by stringhandler** [comment]
This is when a user spends funds from aurora

**Comment by Anziskavds** [comment]
Correct I updated the ticket with the correct steps
