### ISSUE TITLE
User no longer see the Load QR code to restore Tari Universe on Aurora

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#869]
**Describe the bug**
User set the "paper_wallet_enabled" to true and went to Wallet settings. There is no longer the "Link Tari Aurora" option there to scan the QR code and restore the wallet.

**To Reproduce**
1. Set paper_wallet_enabled to true
2. Close Tari Universe 
3. Open Tari Universe
4. Go to wallet settings
5. User doesn'y see the "Link Tari Aurora" section to scan the QR code to restore their wallet 

**Expected behavior**
When the user has set their "paper_wallet_enabled" feature flag to true the user should see the "Link Tari Aurora" in wallet settings.

**Screenshots**
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/a3daf60e-7254-459f-bec8-18d5bb54c33d">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnet 0.5.27

**Comment by stringhandler** [comment]
I'm goign to close this, because new UI is coming to display this in a different way
