### ISSUE TITLE
0.5.28: When Tor is disabled, app shows as disconnected from Tari Network

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#874]
**Describe the bug**
As a user I find when I disable Tor and restart the app.  App appears as disconnected and when I check `Experimental Settings` i see; `Not connected to the Tari Network`

**To Reproduce**
1. User is logged into Tari Universe
2. Click on Settings icon
3. Click on `Experimental`
4. Enable toggle
5. Scroll to `Use Tor`
6. Click on toggle to disable `Use Tor`
7. Click on `Restart Now` CTA within the pop up that appears
8. App restarts
9. When app is opened view connected status icon within App widget
10. Go to Settings > Experimental
11. View Debug section

**Expected behavior**
Even with Tor switched of, user should be connected to the Tari network

**Screenshots**
![Screenshot (143)](https://github.com/user-attachments/assets/c3719e6d-1671-409c-b73f-8dead3652e5b)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, 23H2, Intel core i7

**Logs**

[log (1).zip](https://github.com/user-attachments/files/17409496/log.1.zip)

**Comment by mmrrnn** [comment]
The problem is that we've got few tcp peers. You tried to connect when there wasn't tcp peers at all. It means you really hasn't been connected to the Tari network

@stringhandler

**Comment by Tas4tari** [comment]
Thanks @mmrrnn I see this is still occurring as well now on App version 0.5.56

**Comment by Tas4tari** [comment]
Tested on app version 0.5.58 on Windows 11 and this is no longer occurring

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.60 aand this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.61 aand this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.6.4 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.6 and this did not occur:
![Screenshot (261)](https://github.com/user-attachments/assets/3f299882-129a-4b24-91df-7f6af8c45ab8)
![Screenshot (262)](https://github.com/user-attachments/assets/ed9cf2ee-2977-4a18-8599-c5f0f4751093)
![Screenshot (263)](https://github.com/user-attachments/assets/121d4dd0-38d5-4e09-b2fa-918ca1d2ed4d)
