### ISSUE TITLE
User receives a critical error when they toggle Tor off and restart their miner

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#876]
**Describe the bug**
When a user toggled Tor off and clicked cancel on the restart pop up and manually restarted the miner, on start up the user received a critical error pop up message. I clicked on the close Tari universe button and tried to open Tari Universe again but I got stuck on 43%. I needed to force quite Tari Universe and set Tor to true on visual studio to get Tari Universe up and running again.

Log file: My log file is to big to attached

**To Reproduce**
1. Go to experimental settings
2. Toggle "Use Tor" off
3. Click on Cancel on the restart pop up
4. Go and manually restart the miner
5. Open the miner
6. After start up the user receives a critical error pop up

**Expected behavior**
Miner should restart without an error messages.

**Screenshots**
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/9bc4ae4e-9a9d-4cfa-aa39-493a8a01a948">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnet 0.5.28

**Comment by mmrrnn** [comment]
Couldn't reproduce it and I don't know exactly what we can do about it.
When we turn off the tor, we're looking for tcp connections. I'm thinking whether you've been banned by the peer and there is no other to connect with.

@stringhandler

**Comment by mmrrnn** [comment]
Related to #874

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.5.58 and did not see this occur

**Comment by Tas4tari** [comment]
On Windows, I did not see this occur on version 0.5.61 after a new installation
