### ISSUE TITLE
0.5.30 After connecting to airdrop,  a 1K bonus gems green celebration panel appears with text overwriting other text

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#882]
**Describe the bug**
There is no 1K gem bonus for anything and i wouldn't have been eligible for one.
No real balance change occured.

<img width="365" alt="Screenshot 2024-10-17 at 3 33 53 PM" src="https://github.com/user-attachments/assets/dfe30018-b506-43ad-862f-54e7276652c1">

This is reproducible. Part of the recap experience on app returning to foreground I think.

**Comment by PanchoBubble** [comment]
@metalaureate Do we need this take over when earning gems from mining? or just the gems tickling up?

**Comment by Rudro124** [comment]
Yes

**Comment by brianp** [comment]
Closing. Should be fixed in https://github.com/tari-project/universe/pull/887
