### ISSUE TITLE
User no longer receives hashrate low warning pop up messages

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#886]
**Describe the bug**
When the CPU and/or the GPU Power drops the user no longer receives the hashrate low warning pop up messages.

**To Reproduce**
1. Have Tari Universe running 
2. Keep an eye on the CPU/GPU Power
3. When the CPU/GPU Power drops the user no longer receive the hashrate low warnings

**Expected behavior**
When the CPU/GPU Power drops the user should receive the hashrate low warning messages.

**Screenshots**
https://www.loom.com/share/4f10937df3e54f7894390c24e70ddf8e

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnet 0.5.31

**Comment by brianp** [comment]
Low hash rate warning was intentionally removed.
