### ISSUE TITLE
Users gets stuck on loading state when they enable CPU and GPU Power

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#901]
**Describe the bug**
When a user disabled their CPU and/or GPU Power in mining settings the user gets stuck in a loading state when they enable the CPU and/or GPU Power again.

**To Reproduce**
1. Go to mining settings
2. Disable CPU and/or GPU Power
3. Wait a few minutes
4. Enable the CPU and/or GPU Power again
5. User gets stuck in a loading state

**Expected behavior**
User should be able to disable and enable the CPU and/or GPU Power without getting stuck in the loading state.

**Screenshots**
<img width="361" alt="image" src="https://github.com/user-attachments/assets/0e653187-87ee-4f16-815a-e64ea0ad942f">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 on Sonoma 14.5
 - Browser & Version Testnet 0.5.41

**Additional context**
Log file is too big to share

**Comment by Anziskavds** [comment]
This is also happening on Windows. I tested on Testnet 0.5.45 on a Acer Aspire A315-59 on Windows 11

**Comment by brianp** [comment]
This has been iterated on since reporting, and newer issues created.
