### ISSUE TITLE
Mine for 8 hrs at 833k XTM/day but no XTM

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#91]
[com.tari.universe.zip](https://github.com/user-attachments/files/16700481/com.tari.universe.zip)
**Describe the bug**
Mining for 8 hrs at 700 h/s and 833K XTM/day with no earnings.

![image](https://github.com/user-attachments/assets/81ecfd82-2e94-479b-a254-b1d688b6fda7)

**Expected behavior**
Something coherent with 833K/day XTM estimated earnings

**Desktop (please complete the following information):**
 - OS & Version: Mac M1 Sonoma

**Additional context**
Was working in earlier builds.

**Comment by metalaureate** [comment]
@stringhandler logs as requested Library/Application Support/com.tari.universe

**Comment by stringhandler** [comment]
Moving to Blocked until more cases reported

**Comment by stringhandler** [comment]
Waiting to see if this is still an issue with new builds
