### ISSUE TITLE
XTM must show tXTM and show Testnet

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#92]
**Describe the bug**]
Users will be very confused when mainnet launches unless we distinguish tXTM now from XTM
X and Y will be names given to the next two testnets resets

**Comment by stringhandler** [comment]
@metalaureate what and where do you want to show with regards to "X testnet" and "Y Testnet"

**Comment by metalaureate** [comment]
Placement of Testnet

![image](https://github.com/user-attachments/assets/ebaf3622-525e-420d-84f5-40576b5bc7ff)
