### ISSUE TITLE
0.5.45: Blank white screen on Big Sur

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#922]
**Describe the bug**
![telegram-cloud-photo-size-2-5244536947299444400-m](https://github.com/user-attachments/assets/e04d511b-76ac-48cd-9b97-2d46e1dac835)

![telegram-cloud-photo-size-2-5244536947299444072-y](https://github.com/user-attachments/assets/dabc8786-1234-4c76-85b6-40fc7b44ca66)

This was recently introduced.

**Comment by brianp** [comment]
probably fixed
