### ISSUE TITLE
！

### ISSUE THREAD

**Issue by DWBCoreOfficial** [tari-project/universe#923]
I've been stuck here since the update
![IMG_20241024_143050_009](https://github.com/user-attachments/assets/a7f7c2cf-e434-4461-ad5f-67fb75193207)

**Comment by DWBCoreOfficial** [comment]
Please make the software run as an administrator by default

**Comment by mmrrnn** [comment]
https://github.com/tari-project/universe/pull/712 - Run as an administrator + handle firewall.

**Comment by mmrrnn** [comment]
@DWBCoreOfficial Please attach logs and describe the problem in more detail.
I think the problem may be related to the blocked Tor download source

**Comment by DWBCoreOfficial** [comment]
I will send you the logs tomorrow
