### ISSUE TITLE
！！

### ISSUE THREAD

**Issue by DWBCoreOfficial** [tari-project/universe#924]
The Tor bridge is not functioning properly and cannot connect to the Tari network

**Comment by DWBCoreOfficial** [comment]
![Uploading IMG_20241024_143653.jpg…]()

**Comment by DWBCoreOfficial** [comment]
![IMG_20241024_143653](https://github.com/user-attachments/assets/164e028d-e875-4f55-969c-36ff827156ae)

**Comment by mmrrnn** [comment]
@DWBCoreOfficial Please provide more details along with log files.

**Comment by DWBCoreOfficial** [comment]
> @DWBCoreOfficial请提供更多详细信息以及日志文件。
I have already uploaded the log directly through the software

**Comment by brianp** [comment]
Issue is a month old with many tor fixes. Please try again.
