### ISSUE TITLE
0.5.45 Changing Monero address always errors with invalid format

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#933]
**Describe the bug**
This is with the Donate address for example:

<img width="757" alt="Screenshot 2024-10-24 at 2 35 05 PM" src="https://github.com/user-attachments/assets/52bbef54-2362-41f1-8924-fd3baf91e819">

**Comment by brianp** [comment]
The monero address can't be a subaddress, and must be a mainnet monero address.

With known valid addresses it works fine. Closing as no issue.

**Comment by kwahl45** [comment]
The bug lies in the address beginning, if you use any other monero address that starts with an 8 it will not recognize it

**Comment by kwahl45** [comment]
it will only recognize an address beginning with 4 as a correct address

**Comment by brianp** [comment]
Yup, as i said. Sub-addresses (that start with 8) are not supported. That's not a bug. You must use a mainnet standard address. This is a limitation of xmrig the merge miner.

**Comment by kwahl45** [comment]
If that's tru then why am I able to mine monero with xmrig thru feather
wallet and use an address that starts with 8?

**Comment by brianp** [comment]
🤷🏻‍♂️

**Comment by kwahl45** [comment]
That doesn't help

**Comment by kwahl45** [comment]
Thats fine this project was an interesting idea that I wanted to try out
not everything works out
