### ISSUE TITLE
Minor UI bug: The emoji id address overlaps with each other

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#943]
**Describe the bug**
The bottom row of the emoji id addresas overlaps with the top row of emojis.

**To Reproduce**
1. Go to wallet settings
2. Expand the emoji id address
3. See that the bottom row overlaps with the top row of emojis

**Expected behavior**
Emoji id address should display without any the emojis overlapping each other.

**Screenshots**
<img width="715" alt="image" src="https://github.com/user-attachments/assets/368ac2e9-21ab-4567-a230-9efd5128e220">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 on Sonoma 14.5
 - Browser & Version Testnet 0.5.48

**Comment by brianp** [comment]
Closing as won't fix for now. It's not vital to keep the issue open. 

Pinging @shanimal08 @peps to make them aware if they happen to want to resolve some UI stuff.

**Comment by Tas4tari** [comment]
Tested successfully on Windows 11, app version 0.7.0

**Comment by Anziskavds** [comment]
Tested successfully on a MacBook Air 13 inch M1 2020 ON Testnet v0.8.7
