### ISSUE TITLE
Tor is off by default after new install and after resetting the settings

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#952]
**Describe the bug**
When a user does a new install or reset their setting and they go to Eperimental settings, Tor is disabled by default.

**To Reproduce**
1. Do a new installation or reset settings
2. Wait for the miner to open
3. Go to Experimental settings
4. Scroll down to Tor
5. Tor is disabled by default

**Expected behavior**
Tor should be enabled after a new install or if the settings was reset

**Screenshots**
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/34679a6d-a7f2-4f9a-89a0-15feae2ef31a">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnet v0.5.49

**Comment by brianp** [comment]
Can not confirm.
