### ISSUE TITLE
Block time disappears when they switch to Ludicrous mode

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#953]
**Describe the bug**
When a user switch from ECO mode to Ludicrous mode the block time disappears.
 
**To Reproduce**
1. Let the miner run on ECO mode
2. Switch to Ludicrous mode
3. Look at the block time
4. After switching from ECO to Ludicrous mode the block time no longer shows

**Expected behavior**
Block time should show for ECO and Ludicrous modes

**Screenshots**
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/7320b9ca-6ef9-4c57-991f-a4c0e159a746">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Testnet v0.5.49

**Comment by brianp** [comment]
Possibly fixed. Can not reproduce. Many enhancements made in this area.
