### ISSUE TITLE
Number and date localization is buggy

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#956]
**Describe the bug**

In language settings we are in Russian

![telegram-cloud-photo-size-2-5260703135482110426-x](https://github.com/user-attachments/assets/3bcb78cd-f35e-4ce7-a06e-8c28ce090af6)

It seems that language fix didn't applied to wallet balance and est. earnings. CPU and GPU seems correct.

![telegram-cloud-photo-size-2-5260703135482110429-x](https://github.com/user-attachments/assets/e92d783b-7add-4e3f-ac29-e083a6c78b5b)

Also it still pulls month naming in wallet history from pc language as well - the app is set to use english and use system language is turned off.

**Comment by Anziskavds** [comment]
This tested successfully on MacBook Air 13 inch M1 2020 on Testnet v0.5.63.
