### ISSUE TITLE
Dark mode is set by default on v0.5.51

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#958]
**Describe the bug**
User got the dark mode by default when I installed(fresh install) v0.5.51.

**To Reproduce**
1. Install the new build v0.5.51
2. When the miner opens the dark mode is set by default

**Expected behavior**
User shouldn't receive the dark mode by default.

**Screenshots**
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/5197d0a6-82c2-459d-81da-5f44ed98b42c">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 on Sonoma 14.5
 - Browser & Version Testnet v0.5.51

**Additional context**
Simon is not experiencing the same same but he didn't do a fresh install.

**Comment by Tas4tari** [comment]
This is also occurring on Aspire A315-59, Windows 11 on app version: 0.5.51. I did a fresh install of the build
![Screenshot (156)](https://github.com/user-attachments/assets/dcfa728b-6aef-46f1-9a94-f381650c68d3)

**Comment by brianp** [comment]
This has been fixed.
