### ISSUE TITLE
There is no copy button on the seed phrase unless you select to show the seed phrase

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#959]
**Describe the bug**
When a user goes to wallet setting there is no copy button when the user doesn't select to reveal the seed phrase. 

**To Reproduce**
1. Go to wallet setting
2. Look at the seed word section
3. There is no copy button untill the user select to reveals their seed phrase

**Expected behavior**
User shoul see the copy button on every state

**Video**
https://www.loom.com/share/8db833e5dd7945e3b3dcfb33bda42454

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air M1 2020 Sonoma 14.5
 - Browser & Version Testnet v0.5.51

**Comment by Tas4tari** [comment]
Also visible on app version 0.5.51 on Windows 11

**Comment by Tas4tari** [comment]
This is also occurring on Windows 11 on app version 0.5.53

**Comment by Tas4tari** [comment]
Tested on Windows 11 on app version 0.5.58 and this is still an issue

**Comment by brianp** [comment]
@peps @shanimal08 is this by design or no?

**Comment by brianp** [comment]
This has been confirmed as a bug. User should be able to copy without revealing.

Coming your way @shanimal08

**Comment by Anziskavds** [comment]
This is no longer an issue on a MacBook Air 13 inch M1 2020 on Testnet v0.8.7
