### ISSUE TITLE
CPU and GPU doesn't load after a user disabled and enabled the settings

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/universe#961]
**Describe the bug**
When a user disabled and enabled the CPU or GPU setting and enabled it again the CPU or GPU setting doesn't load after it. It stays on loading.

**To Reproduce**
1. Go to mining settings
2. Disable the CPU and CPU settings
3. Enable the CPU and GPU setting again after 5-10min min
4. User gets stuck on loading state

**Expected behavior**
User shouldn't wait longer than 3-5min for the CPU ang GPU setting to start up again

**Screenshots**
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/47af4fd7-353e-4dfc-bc1d-c1b181d92cea">

**Desktop (please complete the following information):**
 - OS & Version: MacBook Air 13 inch M1 2020 Sonoma 14.5
 - Browser & Version Tsetnet 14.5

**Comment by brianp** [comment]
Can not reproduce. Possible enhancements in this area have solved the problem.
