### ISSUE TITLE
0.5.53: Airdrop Settings: CTA's appear as greyed out

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#968]
**Describe the bug**
As a user when I view the Airdrop Settings section, I find that the CTA's: "Apply Invite Code" and "Disconnect" appear as greyed out as it is very light

**To Reproduce**
**Pre-conditions:**
- User should not be connected to Airdrop within the tari universe app

**Steps**
1. Go to 'tari universe'
2. Click on 'Settings'
3. Scroll down to 'Airdrop'
4. Click on Airdrop
5. View the "Apply Invite Code" CTA
6. Connect to Airdrop by entering a code and follow the prompts to log into Twitter etc
7. User is successfully connected to Airdrop
8. Click on Settings
9. Click on Airdrop
10. View the "Disconnect" CTA text

**Expected behavior**
User should see the text visible and clear to the user, not greyed out

**Screenshots**
![Screenshot (164)](https://github.com/user-attachments/assets/f163316a-e64a-4079-9bf4-1c0a9146fcdd)
![Screenshot (165)](https://github.com/user-attachments/assets/271689dd-b935-4cb6-9bfb-0be71b45247a)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, Version 23H2

**Comment by Tas4tari** [comment]
Tested on Windows 11,on app version 0.5.58 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11,on app version 0.6.4 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11,on app version 0.6.6 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.14 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.15 and this is still an issue

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.16 and this is still an issue

**Comment by shanimal08** [comment]
hmm on 0.6.16 they're alright for me? (but tbf i'm on mac)

| 0.6.16 |
| --- |
| <img width="1003" alt="image" src="https://github.com/user-attachments/assets/5c4f6591-3c1b-42e7-a48a-16e9d91817ae"> |
| <img width="973" alt="image" src="https://github.com/user-attachments/assets/7879632e-a2b1-4a61-835d-65c7ef71bf5d"> |


but i've updated the buttons so they look more like buttons (updated in #1070)

| updated |
| --- |
| <img width="1119" alt="image" src="https://github.com/user-attachments/assets/dc60a91d-b055-4d75-a72b-c376e17cfce1"> |
| <img width="1036" alt="image" src="https://github.com/user-attachments/assets/816c4d16-49f9-48b8-a0d9-353f15224b35"> |

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.6.17 and still an issue, I however see @shanimal08 comment wrt to fixes so when merged I will check once again and close of if rectified

**Comment by Tas4tari** [comment]
Tested on Windows 11, app version 0.7.0 and this is no longer happening
