### ISSUE TITLE
0.5.55 shadows sometimes get stuck for 5 seconds

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#972]
**Describe the bug**
<img width="458" alt="Screenshot 2024-10-29 at 10 56 16 AM" src="https://github.com/user-attachments/assets/5c2406d7-c2a4-4e72-88d9-279ced53c6d8">

On Mac. This happens when miner comes to the foreground after being behind windows.

**Comment by shanimal08** [comment]
it happens on the main Lusion build too ☹️ - i'll try dig in a bit, but they might know off hand what is causing it :D 


<img width="710" alt="image" src="https://github.com/user-attachments/assets/af343992-eff9-4947-a60b-bfe1f580d7ff">

**Comment by Anziskavds** [comment]
Tested successfully on MacBook Air 13 inch M1 2020 on Testnet v0.5.63.
