### ISSUE TITLE
0.5.56 Wallet history shows dates in the wrong month

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#973]
**Describe the bug**
![image](https://github.com/user-attachments/assets/96010430-4770-424e-a5af-be9f437419ae)
This seems to be the result of opening the history panel before the wallet balance has full initialized.

**Comment by brianp** [comment]
Related to https://github.com/tari-project/universe/issues/1093

**Comment by brianp** [comment]
Should be fixed it: https://github.com/tari-project/universe/pull/1146

Feel free to re-open if you find the issue persists.
