### ISSUE TITLE
0.5.60: Windows 11: When app is left to run in the background, it freezes and only a restart of the computer can take it out from this state

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#983]
**Describe the bug**
Issue whereby when app is left to run in the background, it freezes. I tried closing or doing a force quit on the app but that did not work and I had to restart the laptop itself to get out of the state.

**To Reproduce**
1. Go to tari universe app
2. Start mining
3. Leave the app to run in the background
4. After about an hour go back to the app
5. User sees the app frozen

**Expected behavior**
App should not freeze and should have been mining. I should have been able to click within the app or even close the app

**Screenshots**
![Screenshot (179)](https://github.com/user-attachments/assets/13bf8b5c-d833-43ee-87ae-3efd16c0e089)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, version 23H2

**Logs**
File to big to add

**Comment by brianp** [comment]
Feels like an app longevity problem that needs investigation for multiple reasons. But am going to close this for now as without logs, it's too hard for devs to reproduce.
