### ISSUE TITLE
0.5.60: Windows 11: System Tray format: Format on system tray appears as cut off

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/universe#984]
**Describe the bug**
When I view the system tray and hover over the Tari universe icon, the information in the pop up appears cut off

**To Reproduce**
1. Go to tari universe app
2. Start mining
3. Click on `Show hidden icons` at the bottom right of the screen
4. Once tray opens hover over the Tari universe icon
5. View information displayed

**Expected behavior**
User should see information appear clear and concise as per: https://github.com/tari-project/universe/pull/471

**Screenshots**
![Screenshot (182)](https://github.com/user-attachments/assets/b0612084-dfe9-4c96-9230-5e7a16144c9a)

**Desktop (please complete the following information):**
 - Aspire A315-59
 - Windows 11, version 23H2

**Comment by brianp** [comment]
Closing this issue as it's quite stale and systray had been significantly restructured. If you find this to still be an issue feel free to re-open.
