### ISSUE TITLE
Remember experimental settings after update

### ISSUE THREAD

**Issue by palomato** [tari-project/universe#987]
After every auto-update, user must go into settings to re-enable experimental settings.

Client should remember and apply settings after an update. For example, if Visual Mode is unchecked in experimental settings, it should remain unchecked after updating the client.

**Comment by brianp** [comment]
When this issue is tackled see if we can also remember and reset the window position and sizing.

**Comment by brianp** [comment]
Additionally, this issue is expanded to handle windows and linux update situations. When installs are made ontop of previous installs settings are being reset. 

Ensure settings don't get reset after re-installs/upgrades.
