### ISSUE TITLE
Copy Seed words should be disabled unless they are visible

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#99]
v0.1.34

Expected: Copy seed words button in settings should be disabled when they are hidden
Actual: I can copy seed words before showing them

**Comment by mmrrnn** [comment]
decrypting seed words returns an empty array:


https://github.com/user-attachments/assets/a792a983-b90f-4aec-abab-91ae60ee94d1

**Comment by mmrrnn** [comment]
I just needed to remove wallet_config.json and rerun the app
